<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsRoslynComponent>true</IsRoslynComponent>
    <AnalyzerLanguage>cs</AnalyzerLanguage>
    <IsPublishable>false</IsPublishable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeSymbols>false</IncludeSymbols>
    <Description>Source generator for Funge-98 programs.</Description>
    <PackageId>Esolang.Funge.Generator</PackageId>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <DevelopmentDependency>true</DevelopmentDependency>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>esolang;funge;funge-98;befunge;generator;source-generator;roslyn-analyzer</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Esolang.Generator.Abstractions" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="../CHANGELOG.md" Pack="true" PackagePath="\" />
    <None Include="../LICENSE" Pack="true" PackagePath="\" />
    <None Include="buildTransitive\Esolang.Funge.Generator.targets" Pack="true" PackagePath="buildTransitive\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="Rules/*.md" Pack="true" PackagePath="Rules" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Parser\Esolang.Funge.Parser.csproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Esolang.Funge.Generator.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="$(OutputPath)\Esolang.Funge.Parser.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="$(PkgEsolang_Generator_Abstractions)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(PkgEsolang_Generator_Abstractions)\lib\netstandard2.0\*.xml" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
  </ItemGroup>

  <PropertyGroup>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
  </PropertyGroup>

  <Target Name="GetDependencyTargetPaths">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(ProjectDir)..\Parser\$(OutputPath)\*.dll" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>

</Project>
