using Esolang.Funge.Parser;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace Esolang.Funge.Generator;

/// <summary>
/// A source generator that emits method implementations from <c>GenerateFungeMethodAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class MethodGenerator : IIncrementalGenerator
{
    /// <summary>The standard auto-generated file header.</summary>
    public const string CommentAutoGenerated = "// <auto-generated/>";

    /// <summary>The namespace where the generated attribute is placed.</summary>
    public const string NameSpaceName = "Esolang.Funge";

    /// <summary>The generated attribute class name.</summary>
    public const string AttributeName = "GenerateFungeMethodAttribute";

    /// <summary>The source file name used to aggregate generated methods.</summary>
    public const string GeneratedMethodsFileName = "GenerateFungeMethod.g.cs";

    const string GeneratedMethodsFileHeader = $$"""
        {{CommentAutoGenerated}}
        #nullable enable
        #pragma warning disable CS0219
        #pragma warning disable CS1998

        """;

    // -----------------------------------------------------------------------
    // Enumerations for execution signature binding
    // -----------------------------------------------------------------------

    enum ReturnKind
    {
        Void,
        Int,
        String,
        Task,
        TaskInt,
        TaskString,
        ValueTask,
        ValueTaskInt,
        ValueTaskString,
        EnumerableByte,
        AsyncEnumerableByte,
        Invalid,
    }

    enum InputKind { None, String, TextReader, PipeReader }

    enum OutputKind { None, TextWriter, PipeWriter, ReturnString, ReturnEnumerable, ReturnAsyncEnumerable }

    readonly struct KnownTypes
    {
        public readonly INamedTypeSymbol? String;
        public readonly INamedTypeSymbol? Task;
        public readonly INamedTypeSymbol? TaskInt;
        public readonly INamedTypeSymbol? TaskString;
        public readonly INamedTypeSymbol? ValueTask;
        public readonly INamedTypeSymbol? ValueTaskInt;
        public readonly INamedTypeSymbol? ValueTaskString;
        public readonly INamedTypeSymbol? IEnumerableByte;
        public readonly INamedTypeSymbol? IAsyncEnumerableByte;
        public readonly INamedTypeSymbol? Byte;
        public readonly INamedTypeSymbol? Int;
        public readonly INamedTypeSymbol? TextReader;
        public readonly INamedTypeSymbol? PipeReader;
        public readonly INamedTypeSymbol? TextWriter;
        public readonly INamedTypeSymbol? PipeWriter;
        public readonly INamedTypeSymbol? CancellationToken;
        public readonly INamedTypeSymbol? ILogger;
        public readonly INamedTypeSymbol? ILoggerOfT;

        public KnownTypes(Compilation compilation)
        {
            String = compilation.GetSpecialType(SpecialType.System_String);
            var byteSymbol = compilation.GetSpecialType(SpecialType.System_Byte);
            var intSymbol = compilation.GetSpecialType(SpecialType.System_Int32);
            
            var taskGeneric = GetBestTypeByMetadataName(compilation, "System.Threading.Tasks.Task`1");
            Task = GetBestTypeByMetadataName(compilation, "System.Threading.Tasks.Task");
            TaskInt = taskGeneric?.Construct(intSymbol);
            TaskString = taskGeneric?.Construct(String);

            var valueTaskGeneric = GetBestTypeByMetadataName(compilation, "System.Threading.Tasks.ValueTask`1");
            ValueTask = GetBestTypeByMetadataName(compilation, "System.Threading.Tasks.ValueTask");
            ValueTaskInt = valueTaskGeneric?.Construct(intSymbol);
            ValueTaskString = valueTaskGeneric?.Construct(String);

            var enumerableGeneric = GetBestTypeByMetadataName(compilation, "System.Collections.Generic.IEnumerable`1");
            IEnumerableByte = enumerableGeneric?.Construct(byteSymbol);

            var asyncEnumerableGeneric = GetBestTypeByMetadataName(compilation, "System.Collections.Generic.IAsyncEnumerable`1");
            IAsyncEnumerableByte = asyncEnumerableGeneric?.Construct(byteSymbol);

            Byte = byteSymbol;
            Int = intSymbol;
            TextReader = GetBestTypeByMetadataName(compilation, "System.IO.TextReader");
            PipeReader = GetBestTypeByMetadataName(compilation, "System.IO.Pipelines.PipeReader");
            TextWriter = GetBestTypeByMetadataName(compilation, "System.IO.TextWriter");
            PipeWriter = GetBestTypeByMetadataName(compilation, "System.IO.Pipelines.PipeWriter");
            CancellationToken = GetBestTypeByMetadataName(compilation, "System.Threading.CancellationToken");
            ILogger = GetBestTypeByMetadataName(compilation, "Microsoft.Extensions.Logging.ILogger");
            ILoggerOfT = GetBestTypeByMetadataName(compilation, "Microsoft.Extensions.Logging.ILogger`1");
        }

        private static INamedTypeSymbol? GetBestTypeByMetadataName(Compilation compilation, string metadataName)
        {
            var type = compilation.GetTypeByMetadataName(metadataName);
            if (type != null) return type;

            // Manual search through references if the standard lookup fails due to ambiguity
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
            {
                var found = assembly.GetTypeByMetadataName(metadataName);
                if (found != null) return found;
            }
            return null;
        }
    }

    readonly struct ExecutionBinding(
        bool isValid,
        ReturnKind returnKind,
        InputKind inputKind,
        OutputKind outputKind,
        string inputExpression,
        string outputExpression,
        string? argsExpression,
        string? envsExpression,
        string? cancellationTokenName,
        string? loggerExpression,
        bool isLoggerFromParameter,
        string? errorId,
        Location? location = null)
    {
        public bool IsValid { get; } = isValid;
        public ReturnKind ReturnKind { get; } = returnKind;
        public InputKind InputKind { get; } = inputKind;
        public OutputKind OutputKind { get; } = outputKind;
        public string InputExpression { get; } = inputExpression;
        public string OutputExpression { get; } = outputExpression;
        public string? ArgsExpression { get; } = argsExpression;
        public string? EnvsExpression { get; } = envsExpression;
        public string? CancellationTokenName { get; } = cancellationTokenName;
        public string? LoggerExpression { get; } = loggerExpression;
        public bool IsLoggerFromParameter { get; } = isLoggerFromParameter;
        public string? ErrorId { get; } = errorId;
        public Location? Location { get; } = location;
        public bool HasExplicitInput => InputKind is not InputKind.None;
        public bool HasExplicitOutput => OutputKind is not OutputKind.None;
    }

    // -----------------------------------------------------------------------
    // IIncrementalGenerator.Initialize
    // -----------------------------------------------------------------------

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("GenerateFungeMethodAttribute.cs", $$"""
                {{CommentAutoGenerated}}
                using System;
                using System.Diagnostics;
                namespace {{NameSpaceName}} {
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                    internal sealed class {{AttributeName}} : Attribute
                    {
                        /// <summary>
                        /// Generate a Funge-98 method implementation from a source file.
                        /// </summary>
                        /// <param name="sourcePath">Path to the Funge-98 source file (.b98). Ignored when <see cref="InlineSource"/> is set.</param>
                        internal {{AttributeName}}(string sourcePath = "") { }
                        /// <summary>
                        /// Inline Funge-98 source code. When non-empty, <c>sourcePath</c> is ignored.
                        /// </summary>
                        public string InlineSource = "";
                    }
                }
                """));

        const string fullAttributeName = NameSpaceName + "." + AttributeName;
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullAttributeName,
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => ctx);

        var generatedTargets = source.Collect();

        var additionalFiles = context.AdditionalTextsProvider
            .Select(static (text, token) => (text.Path, Text: text.GetText(token)?.ToString()))
            .Collect();

        var languageVersion = context.ParseOptionsProvider
            .Select(static (opts, _) =>
                opts is CSharpParseOptions csOpts ? csOpts.LanguageVersion : LanguageVersion.Default);

        var projectDirectory = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
                provider.GlobalOptions.TryGetValue("build_property.MSBuildProjectDirectory", out var dir)
                || provider.GlobalOptions.TryGetValue("build_property.ProjectDir", out dir)
                ? dir : null);

        var compilation = context.CompilationProvider;
        var knownTypes = compilation.Select(static (c, _) => new KnownTypes(c));

        var inputs = generatedTargets
            .Combine(additionalFiles)
            .Combine(languageVersion)
            .Combine(projectDirectory)
            .Combine(compilation)
            .Combine(knownTypes);

        context.RegisterSourceOutput(inputs, static (ctx, input) =>
        {
            var (((((sources, files), langVersion), projDir), compilation), types) = input;

            if (sources.IsDefaultOrEmpty)
                return;

            var methodSb = new StringBuilder(GeneratedMethodsFileHeader);
            var emittedCount = 0;
            var runtimeFeatures = RuntimeFacadeFeatures.None;

            foreach (var syntaxCtx in sources)
            {
                var method = (MethodDeclarationSyntax)syntaxCtx.TargetNode;
                var symbol = (IMethodSymbol)syntaxCtx.TargetSymbol;

                if (!IsLanguageVersionAtLeastCSharp8(langVersion))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.LanguageVersionTooLow,
                        method.Identifier.GetLocation(),
                        langVersion.ToDisplayString()));
                }

                // Get sourcePath attribute argument
                var attrData = syntaxCtx.Attributes.FirstOrDefault();
                if (attrData is null) continue;

                string? sourcePath = null;
                if (attrData.ConstructorArguments.Length > 0)
                {
                    sourcePath = attrData.ConstructorArguments[0].Value as string;
                }
                else
                {
                    // Fallback to syntax if semantic model couldn't resolve
                    var attributeSyntax = attrData.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
                    if (attributeSyntax?.ArgumentList?.Arguments.Count > 0)
                    {
                        var arg = attributeSyntax.ArgumentList.Arguments[0].Expression;
                        if (arg is LiteralExpressionSyntax lit)
                        {
                            sourcePath = lit.Token.ValueText;
                        }
                    }
                }

                // Check for inline source (named argument takes priority over file path)
                string? inlineSource = null;
                foreach (var namedArg in attrData.NamedArguments)
                {
                    if (namedArg.Key == "InlineSource")
                    {
                        inlineSource = namedArg.Value.Value as string;
                        break;
                    }
                }
                
                if (inlineSource == null)
                {
                     var attributeSyntax = attrData.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
                     if (attributeSyntax?.ArgumentList != null)
                     {
                         foreach (var arg in attributeSyntax.ArgumentList.Arguments)
                         {
                             if (arg.NameEquals?.Name.Identifier.ValueText == "InlineSource" && arg.Expression is LiteralExpressionSyntax lit)
                             {
                                 inlineSource = lit.Token.ValueText;
                             }
                         }
                     }
                }

                if (string.IsNullOrWhiteSpace(inlineSource) && string.IsNullOrWhiteSpace(sourcePath))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InvalidSourcePathParameter,
                        method.Identifier.GetLocation(),
                        symbol.Name));
                    continue;
                }

                // Bind the method signature
                var binding = BindExecutionSignature(symbol, method, types);
                if (!binding.IsValid)
                {
                    if (binding.ErrorId == DiagnosticDescriptors.InvalidReturnType.Id)
                        ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidReturnType,
                            binding.Location ?? method.Identifier.GetLocation(),
                            symbol.ReturnType.ToDisplayString()));
                    else if (binding.ErrorId == DiagnosticDescriptors.DuplicateParameter.Id)
                        ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.DuplicateParameter,
                            binding.Location ?? method.Identifier.GetLocation(),
                            symbol.Name, symbol.Name));
                    else if (binding.ErrorId == DiagnosticDescriptors.ReturnOutputConflict.Id)
                        ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.ReturnOutputConflict,
                            binding.Location ?? method.Identifier.GetLocation(),
                            symbol.Name));
                    else
                        ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidParameter,
                            binding.Location ?? method.Identifier.GetLocation(),
                            symbol.Name));
                    continue;
                }

                // Resolve source text: inline takes priority over file
                string? sourceText = null;
                if (!string.IsNullOrWhiteSpace(inlineSource))
                {
                    sourceText = inlineSource;
                }
                else
                {
                    foreach (var (filePath, fileText) in files)
                    {
                        if (filePath is null || fileText is null) continue;
                        var normalizedSource = NormalizePath(sourcePath!);
                        var normalizedFile = NormalizePath(filePath);
                        // Strip the ".funge.txt" intermediate suffix that the .targets file appends
                        const string fungeSuffix = ".funge.txt";
                        var compareFile = normalizedFile.EndsWith(fungeSuffix, StringComparison.OrdinalIgnoreCase)
                            ? normalizedFile.Substring(0, normalizedFile.Length - fungeSuffix.Length)
                            : normalizedFile;
                        if (string.Equals(compareFile, normalizedSource, StringComparison.OrdinalIgnoreCase)
                            || compareFile.EndsWith("/" + normalizedSource, StringComparison.OrdinalIgnoreCase)
                            || string.Equals(System.IO.Path.GetFileName(compareFile),
                                   System.IO.Path.GetFileName(normalizedSource), StringComparison.OrdinalIgnoreCase))
                        {
                            sourceText = fileText;
                            break;
                        }
                    }

                    if (sourceText is null)
                    {
                        ctx.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticDescriptors.SourceFileNotFound,
                            method.Identifier.GetLocation(),
                            sourcePath));
                        continue;
                    }
                }

                // Parse the Funge space
                var space = FungeParser.Parse(sourceText!);

                // Scan for I/O usage
                var (usesOutput, usesInput) = ScanFungeIo(space);

                if (usesOutput && !binding.HasExplicitOutput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.RequiredOutputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                if (usesInput && !binding.HasExplicitInput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.RequiredInputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                if (!usesInput && binding.HasExplicitInput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.UnusedInputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                var displayPath = !string.IsNullOrWhiteSpace(inlineSource) ? "<inline>" : sourcePath!;
                var emitted = EmitMethod(symbol, method, space, binding, projDir, displayPath);
                methodSb.AppendLine(emitted);
                emittedCount++;
                runtimeFeatures |= GetRuntimeFacadeFeatures(binding.ReturnKind);
                if (binding.LoggerExpression is not null)
                    runtimeFeatures |= RuntimeFacadeFeatures.RunWithLogging;
            }

            if (emittedCount > 0)
                ctx.AddSource(GeneratedMethodsFileName, methodSb.ToString());

            EmitRuntimeIfNeeded(ctx, runtimeFeatures);
        });
    }

    static RuntimeFacadeFeatures GetRuntimeFacadeFeatures(ReturnKind returnKind) => returnKind switch
    {
        ReturnKind.Void or ReturnKind.Int => RuntimeFacadeFeatures.RunSync,
        ReturnKind.String => RuntimeFacadeFeatures.RunString,
        ReturnKind.Task => RuntimeFacadeFeatures.RunTask,
        ReturnKind.TaskInt => RuntimeFacadeFeatures.RunTaskInt,
        ReturnKind.TaskString => RuntimeFacadeFeatures.RunTaskString,
        ReturnKind.ValueTask => RuntimeFacadeFeatures.RunValueTask,
        ReturnKind.ValueTaskInt => RuntimeFacadeFeatures.RunValueTaskInt,
        ReturnKind.ValueTaskString => RuntimeFacadeFeatures.RunValueTaskString,
        ReturnKind.EnumerableByte => RuntimeFacadeFeatures.RunEnumerable,
        ReturnKind.AsyncEnumerableByte => RuntimeFacadeFeatures.RunAsyncEnumerable,
        _ => RuntimeFacadeFeatures.None,
    };

    // -----------------------------------------------------------------------
    // Signature binding
    // -----------------------------------------------------------------------

    static bool IsSameType(ITypeSymbol? type, INamedTypeSymbol? knownType)
    {
        if (type is null || knownType is null) return false;
        return SymbolEqualityComparer.Default.Equals(type, knownType);
    }

    static bool IsSameTypeOrConstructedFrom(ITypeSymbol? type, INamedTypeSymbol? knownType)
    {
        if (type is null || knownType is null) return false;
        if (SymbolEqualityComparer.Default.Equals(type, knownType)) return true;
        if (type is INamedTypeSymbol namedType && namedType.IsGenericType && SymbolEqualityComparer.Default.Equals(namedType.ConstructedFrom, knownType)) return true;
        return false;
    }

    static bool IsLoggerType(ITypeSymbol? type, KnownTypes types)
    {
        if (type is null) return false;
        if (IsSameType(type, types.ILogger) || IsSameTypeOrConstructedFrom(type, types.ILoggerOfT)) return true;

        foreach (var iface in type.AllInterfaces)
        {
            if (IsSameType(iface, types.ILogger) || IsSameTypeOrConstructedFrom(iface, types.ILoggerOfT)) return true;
        }
        return false;
    }

    static ExecutionBinding BindExecutionSignature(IMethodSymbol method, MethodDeclarationSyntax syntax, KnownTypes types)
    {
        var returnType = method.ReturnType;

        var returnKind = ReturnKind.Invalid;

        if (returnType.SpecialType == SpecialType.System_Void) returnKind = ReturnKind.Void;
        else if (returnType.SpecialType == SpecialType.System_Int32) returnKind = ReturnKind.Int;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.String)) returnKind = ReturnKind.String;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.Task)) returnKind = ReturnKind.Task;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.TaskInt)) returnKind = ReturnKind.TaskInt;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.TaskString)) returnKind = ReturnKind.TaskString;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.ValueTask)) returnKind = ReturnKind.ValueTask;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.ValueTaskInt)) returnKind = ReturnKind.ValueTaskInt;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.ValueTaskString)) returnKind = ReturnKind.ValueTaskString;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.IEnumerableByte)) returnKind = ReturnKind.EnumerableByte;
        else if (SymbolEqualityComparer.Default.Equals(returnType, types.IAsyncEnumerableByte)) returnKind = ReturnKind.AsyncEnumerableByte;

        if (returnKind == ReturnKind.Invalid)
        {
             // returnKind is invalid, check types for debugging
             // Using a diagnostic for debugging as we are in a generator
             // ctx.ReportDiagnostic(...); // Need context here, but BindExecutionSignature doesn't have it. 
             // We'll have to return an error diagnostic later in Initialize.
             // For now, let's keep returnKind as invalid to trigger the error.
        }
        
        if (returnKind == ReturnKind.Invalid)
            return new(false, returnKind, InputKind.None, OutputKind.None, "", "", null, null, null, null, false,
                DiagnosticDescriptors.InvalidReturnType.Id);

        var outputKind = returnKind switch
        {
            ReturnKind.String or ReturnKind.TaskString or ReturnKind.ValueTaskString
                => OutputKind.ReturnString,
            ReturnKind.EnumerableByte => OutputKind.ReturnEnumerable,
            ReturnKind.AsyncEnumerableByte => OutputKind.ReturnAsyncEnumerable,
            _ => OutputKind.None,
        };

        var inputKind = InputKind.None;
        var inputExpr = "";
        var outputExpr = "";
        string? argsExpr = null;
        string? envsExpr = null;
        string? cancellationTokenName = null;
        var hasCancellationToken = false;

        string? loggerExpression = null;
        var isLoggerFromParameter = false;

        foreach (var p in method.Parameters)
        {
            if (p.RefKind is not RefKind.None)
                return new(false, returnKind, inputKind, outputKind, "", "", null, null, null, null, false,
                    DiagnosticDescriptors.InvalidParameter.Id, p.Locations.FirstOrDefault());

            var typeName = p.Type.ToDisplayString();

            if (IsLoggerType(p.Type, types))
            {
                if (loggerExpression is not null)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, outputExpr, argsExpr, envsExpr,
                        cancellationTokenName, null, false, DiagnosticDescriptors.DuplicateParameter.Id,
                        p.Locations.FirstOrDefault());
                loggerExpression = p.Name;
                isLoggerFromParameter = true;
                continue;
            }

            if (typeName == "string")
            {
                if (inputKind is not InputKind.None)
                    return new(false, returnKind, inputKind, outputKind, "", "", null, null, null, null, false,
                        DiagnosticDescriptors.DuplicateParameter.Id, p.Locations.FirstOrDefault());
                inputKind = InputKind.String;
                inputExpr = p.Name;
                continue;
            }

            // String array or IEnumerable<string>
            if (p.Type is IArrayTypeSymbol || (p.Type is INamedTypeSymbol namedType && (namedType.Name == "IEnumerable" || namedType.Name == "IEnumerable`1")))
            {
                // This is a rough check, keeping existing logic
                var name = p.Name.ToLowerInvariant();
                if (name.Contains("arg"))
                {
                    if (argsExpr is not null)
                        return new(false, returnKind, inputKind, outputKind, inputExpr, outputExpr, null, null, null, null, false,
                            DiagnosticDescriptors.DuplicateParameter.Id, p.Locations.FirstOrDefault());
                    argsExpr = p.Name;
                    continue;
                }
                if (name.Contains("env"))
                {
                    if (envsExpr is not null)
                        return new(false, returnKind, inputKind, outputKind, inputExpr, outputExpr, null, null, null, null, false,
                            DiagnosticDescriptors.DuplicateParameter.Id, p.Locations.FirstOrDefault());
                    envsExpr = p.Name;
                    continue;
                }
            }

            if (typeName.Contains("TextReader"))
            {
                if (inputKind is not InputKind.None)
                    return new(false, returnKind, inputKind, outputKind, "", "", null, null, null, null, false,
                        DiagnosticDescriptors.DuplicateParameter.Id, p.Locations.FirstOrDefault());
                inputKind = InputKind.TextReader;
                inputExpr = p.Name;
                continue;
            }

            if (typeName.Contains("PipeReader"))
            {
                if (inputKind is not InputKind.None)
                    return new(false, returnKind, inputKind, outputKind, "", "", null, null, null, null, false,
                        DiagnosticDescriptors.DuplicateParameter.Id, p.Locations.FirstOrDefault());
                inputKind = InputKind.PipeReader;
                inputExpr = p.Name;
                continue;
            }

            if (typeName.Contains("PipeWriter"))
            {
                if (outputKind is OutputKind.ReturnString or OutputKind.ReturnEnumerable or OutputKind.ReturnAsyncEnumerable)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, p.Name, null, null,
                        cancellationTokenName, null, false, DiagnosticDescriptors.ReturnOutputConflict.Id,
                        p.Locations.FirstOrDefault());
                if (outputKind is not OutputKind.None)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, p.Name, null, null,
                        cancellationTokenName, null, false, DiagnosticDescriptors.DuplicateParameter.Id,
                        p.Locations.FirstOrDefault());
                outputKind = OutputKind.PipeWriter;
                outputExpr = p.Name;
                continue;
            }

            if (typeName.Contains("TextWriter"))
            {
                if (outputKind is OutputKind.ReturnString or OutputKind.ReturnEnumerable or OutputKind.ReturnAsyncEnumerable)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, p.Name, null, null,
                        cancellationTokenName, null, false, DiagnosticDescriptors.ReturnOutputConflict.Id,
                        p.Locations.FirstOrDefault());
                if (outputKind is not OutputKind.None)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, p.Name, null, null,
                        cancellationTokenName, null, false, DiagnosticDescriptors.DuplicateParameter.Id,
                        p.Locations.FirstOrDefault());
                outputKind = OutputKind.TextWriter;
                outputExpr = p.Name;
                continue;
            }

            if (typeName.Contains("CancellationToken"))
            {
                if (hasCancellationToken)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, outputExpr, null, null,
                        cancellationTokenName, null, false, DiagnosticDescriptors.DuplicateParameter.Id,
                        p.Locations.FirstOrDefault());
                hasCancellationToken = true;
                cancellationTokenName = p.Name;
                continue;
            }

            return new(false, returnKind, inputKind, outputKind, inputExpr, outputExpr, null, null,
                cancellationTokenName, null, false, DiagnosticDescriptors.InvalidParameter.Id,
                p.Locations.FirstOrDefault());
        }

        var fieldName = FindLoggerField(method.ContainingType, method.IsStatic, types, out var isField);
        if (loggerExpression == null)
        {
            loggerExpression = fieldName;
            isLoggerFromParameter = !isField;
        }

        return new(true, returnKind, inputKind, outputKind, inputExpr, outputExpr, argsExpr, envsExpr, cancellationTokenName, loggerExpression, isLoggerFromParameter, null);
    }

    static string? FindLoggerField(ITypeSymbol? type, bool isStatic, KnownTypes types, out bool isField)
    {
        isField = false;
        var isBaseType = false;
        var shadowedNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal);
        var currentType = type;

        while (currentType != null)
        {
            foreach (var field in currentType.GetMembers().OfType<IFieldSymbol>())
            {
                if (isStatic && !field.IsStatic) continue;

                // If searching in a base type, the field must be accessible (protected or public)
                if (isBaseType && field.DeclaredAccessibility is not (Accessibility.Protected or Accessibility.ProtectedOrInternal or Accessibility.Public or Accessibility.Internal))
                    continue;

                if (IsLoggerType(field.Type, types))
                {
                    isField = true;
                    return field.Name;
                }
                else if (field.CanBeReferencedByName)
                {
                    shadowedNames.Add(field.Name);
                }
            }
            currentType = currentType.BaseType;
            isBaseType = true;
        }

        if (type is INamedTypeSymbol namedType)
        {
            foreach (var constructor in namedType.InstanceConstructors)
            {
                if (constructor.DeclaringSyntaxReferences.Any(ds => ds.GetSyntax() is ClassDeclarationSyntax))
                {
                    foreach (var parameter in constructor.Parameters)
                    {
                        if (IsLoggerType(parameter.Type, types) && !shadowedNames.Contains(parameter.Name))
                        {
                            isField = false;
                            return parameter.Name;
                        }
                    }
                }
            }
        }
        return null;
    }

    // -----------------------------------------------------------------------
    // Method emit
    // -----------------------------------------------------------------------

    static string EmitMethod(
        IMethodSymbol symbol,
        MethodDeclarationSyntax syntax,
        FungeSpace space,
        ExecutionBinding binding,
        string? projDir,
        string sourcePath)
    {
        var ns = symbol.ContainingType.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingType.ContainingNamespace.ToDisplayString() : null;

        var typeKeyword = symbol.ContainingType.TypeKind switch
        {
            TypeKind.Struct when symbol.ContainingType.IsRecord => "record struct",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            TypeKind.Class when symbol.ContainingType.IsRecord => "record",
            _ => "class",
        };

        var typeName = symbol.ContainingType.Name;
        var accessibility = GetAccessibility(symbol.DeclaredAccessibility);
        var staticMod = symbol.IsStatic ? " static" : string.Empty;
        var asyncMod = binding.ReturnKind == ReturnKind.AsyncEnumerableByte ? " async" : string.Empty;
        var returnTypeSyntax = symbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var paramList = string.Join(", ", Enumerable.Select(symbol.Parameters, p =>
        {
            var prefix = (binding.ReturnKind == ReturnKind.AsyncEnumerableByte
                && binding.CancellationTokenName is not null
                && string.Equals(p.Name, binding.CancellationTokenName, StringComparison.Ordinal))
                ? "[global::System.Runtime.CompilerServices.EnumeratorCancellation] "
                : string.Empty;
            return prefix + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + " " + p.Name;
        }));

        var relPath = projDir is not null ? MakeRelative(projDir, sourcePath) : sourcePath;
        var sb = new StringBuilder();

        if (ns is not null) { sb.Append("namespace ").Append(ns).AppendLine(" {").AppendLine(); }
        sb.Append("partial ").Append(typeKeyword).Append(' ').AppendLine(typeName);
        sb.AppendLine("{");
        sb.AppendLine($"    // Generated from: {relPath}");
        sb.Append("    ").Append(accessibility).Append(staticMod).Append(asyncMod)
            .Append(" partial ").Append(returnTypeSyntax).Append(' ')
            .Append(symbol.Name).Append('(').Append(paramList).AppendLine(")");
        sb.AppendLine("    {");

        EmitBody(sb, space, binding, symbol.IsStatic);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        if (ns is not null) sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitBody(StringBuilder sb, FungeSpace space, ExecutionBinding binding, bool isStatic)
    {
        var inputExpr = binding.InputKind switch
        {
            InputKind.None => "global::System.IO.TextReader.Null",
            InputKind.String => $"new global::System.IO.StringReader({binding.InputExpression} ?? string.Empty)",
            InputKind.TextReader => binding.InputExpression,
            InputKind.PipeReader => $"new global::System.IO.StreamReader({binding.InputExpression}.AsStream())",
            _ => "global::System.IO.TextReader.Null",
        };
        var cancellationTokenExpr = binding.CancellationTokenName is null
            ? "global::System.Threading.CancellationToken.None"
            : binding.CancellationTokenName;
        var argsExpr = binding.ArgsExpression ?? "null";
        var envsExpr = binding.EnvsExpression ?? "null";

        EmitSpaceData(sb, space);

        var loggerExpr = "";
        if (binding.LoggerExpression is not null)
        {
            var prefix = (!isStatic && !binding.IsLoggerFromParameter) ? "this." : "";
            loggerExpr = $", logger: {prefix}{binding.LoggerExpression}";
        }

        switch (binding.ReturnKind)
        {
            case ReturnKind.Void:
                {
                    if (binding.OutputKind == OutputKind.PipeWriter)
                    {
                        sb.AppendLine($"""
                using var __fungeOutput = new global::System.IO.StreamWriter({binding.OutputExpression}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);
                global::Esolang.Funge.__Generated.FungeRuntime.RunSync(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == OutputKind.TextWriter
                            ? binding.OutputExpression
                            : "global::System.IO.TextWriter.Null";
                        sb.AppendLine($"""
                global::Esolang.Funge.__Generated.FungeRuntime.RunSync(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                    }
                    break;
                }

            case ReturnKind.Int:
                if (binding.OutputKind == OutputKind.PipeWriter)
                {
                    sb.AppendLine($"""
                using var __fungeOutput = new global::System.IO.StreamWriter({binding.OutputExpression}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);
                return global::Esolang.Funge.__Generated.FungeRuntime.RunSync(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                }
                else
                {
                    var outExpr = binding.OutputKind == OutputKind.TextWriter
                        ? binding.OutputExpression
                        : "global::System.IO.TextWriter.Null";
                    sb.AppendLine($"""
                return global::Esolang.Funge.__Generated.FungeRuntime.RunSync(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                }
                break;

            case ReturnKind.String:
                sb.AppendLine($"""
                return global::Esolang.Funge.__Generated.FungeRuntime.RunString(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                break;

            case ReturnKind.Task:
                {
                    if (binding.OutputKind == OutputKind.PipeWriter)
                    {
                        sb.AppendLine($"""
                using var __fungeOutput = new global::System.IO.StreamWriter({binding.OutputExpression}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);
                return global::Esolang.Funge.__Generated.FungeRuntime.RunTask(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == OutputKind.TextWriter
                            ? binding.OutputExpression
                            : "global::System.IO.TextWriter.Null";
                        sb.AppendLine($"""
                return global::Esolang.Funge.__Generated.FungeRuntime.RunTask(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                    }
                    break;
                }

            case ReturnKind.TaskInt:
                if (binding.OutputKind == OutputKind.PipeWriter)
                {
                    sb.AppendLine($$"""
                return __RunTaskIntWithPipeWriter();

                async global::System.Threading.Tasks.Task<int> __RunTaskIntWithPipeWriter()
                {
                    using var __fungeOutput = new global::System.IO.StreamWriter({{binding.OutputExpression}}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);
                    return await global::Esolang.Funge.__Generated.FungeRuntime.RunTaskInt(
                        __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {{inputExpr}}, __fungeOutput, {{(binding.HasExplicitInput ? "true" : "false")}}, {{(binding.HasExplicitOutput ? "true" : "false")}}, {{cancellationTokenExpr}}, {{argsExpr}}, {{envsExpr}}{{loggerExpr}});
                }
        """);
                }
                else
                {
                    var outExpr = binding.OutputKind == OutputKind.TextWriter
                        ? binding.OutputExpression
                        : "global::System.IO.TextWriter.Null";
                    sb.AppendLine($"""
                return global::Esolang.Funge.__Generated.FungeRuntime.RunTaskInt(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                }
                break;

            case ReturnKind.TaskString:
                sb.AppendLine($"""
                return global::Esolang.Funge.__Generated.FungeRuntime.RunTaskString(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                break;

            case ReturnKind.ValueTask:
                {
                    if (binding.OutputKind == OutputKind.PipeWriter)
                    {
                        sb.AppendLine($"""
                using var __fungeOutput = new global::System.IO.StreamWriter({binding.OutputExpression}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);
                return global::Esolang.Funge.__Generated.FungeRuntime.RunValueTask(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == OutputKind.TextWriter
                            ? binding.OutputExpression
                            : "global::System.IO.TextWriter.Null";
                        sb.AppendLine($"""
                return global::Esolang.Funge.__Generated.FungeRuntime.RunValueTask(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                    }
                    break;
                }

            case ReturnKind.ValueTaskInt:
                if (binding.OutputKind == OutputKind.PipeWriter)
                {
                    sb.AppendLine($$"""
                return __RunValueTaskIntWithPipeWriter();
        
                async global::System.Threading.Tasks.ValueTask<int> __RunValueTaskIntWithPipeWriter()
                {
                    using var __fungeOutput = new global::System.IO.StreamWriter({{binding.OutputExpression}}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);
                    return await global::Esolang.Funge.__Generated.FungeRuntime.RunValueTaskInt(
                        __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {{inputExpr}}, __fungeOutput, {{(binding.HasExplicitInput ? "true" : "false")}}, {{(binding.HasExplicitOutput ? "true" : "false")}}, {{cancellationTokenExpr}}, {{argsExpr}}, {{envsExpr}}{{loggerExpr}});
                }
        """);
                }
                else
                {
                    var outExpr = binding.OutputKind == OutputKind.TextWriter
                        ? binding.OutputExpression
                        : "global::System.IO.TextWriter.Null";
                    sb.AppendLine($"""
                return global::Esolang.Funge.__Generated.FungeRuntime.RunValueTaskInt(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                }
                break;

            case ReturnKind.ValueTaskString:
                sb.AppendLine($"""
                return global::Esolang.Funge.__Generated.FungeRuntime.RunValueTaskString(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr});
        """);
                break;

            case ReturnKind.EnumerableByte:
                sb.AppendLine($"""
                foreach (var __b in global::Esolang.Funge.__Generated.FungeRuntime.RunEnumerable(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}))
                    yield return __b;
        """);
                break;

            case ReturnKind.AsyncEnumerableByte:
                sb.AppendLine($"""
                await foreach (var __b in global::Esolang.Funge.__Generated.FungeRuntime.RunAsyncEnumerable(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}))
                    yield return __b;
        """);
                break;
        }
    }

    static void EmitRuntimeRunCall(StringBuilder sb, string inputExpr, string outputExpr, bool hasInput, bool hasOutput)
     => sb.AppendLine($"""
                global::Esolang.Funge.__Generated.FungeRuntime.Run(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outputExpr}, {(hasInput ? "true" : "false")}, {(hasOutput ? "true" : "false")});
        """);

    static void EmitSpaceData(StringBuilder sb, FungeSpace space)
    {
        sb.AppendLine($"""
                int __minX = {space.MinX}, __minY = {space.MinY}, __minZ = {space.MinZ}, __maxX = {space.MaxX}, __maxY = {space.MaxY}, __maxZ = {space.MaxZ};
                var __cells = new global::System.Collections.Generic.Dictionary<(int, int, int), int>();
        """);
        for (var z = space.MinZ; z <= space.MaxZ; z++)
            for (var y = space.MinY; y <= space.MaxY; y++)
                for (var x = space.MinX; x <= space.MaxX; x++)
                {
                    var val = space[new FungeVector(x, y, z)];
                    if (val != ' ')
                        sb.AppendLine($"""
                __cells[({x}, {y}, {z})] = {val};
        """);
                }
    }

    // -----------------------------------------------------------------------
    // I/O scan
    // -----------------------------------------------------------------------

    static (bool usesOutput, bool usesInput) ScanFungeIo(FungeSpace space)
    {
        bool usesOutput = false, usesInput = false;
        for (var z = space.MinZ; z <= space.MaxZ; z++)
            for (var y = space.MinY; y <= space.MaxY; y++)
                for (var x = space.MinX; x <= space.MaxX; x++)
                {
                    var c = space[new FungeVector(x, y, z)];
                    if (c is '.' or ',') usesOutput = true;
                    if (c is '&' or '~') usesInput = true;
                    if (usesOutput && usesInput) return (true, true);
                }
        return (usesOutput, usesInput);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Protected => "protected",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => string.Empty,
    };

    static bool IsLanguageVersionAtLeastCSharp8(LanguageVersion v) => v switch
    {
        LanguageVersion.Default => true,
        LanguageVersion.Latest => true,
        LanguageVersion.Preview => true,
        LanguageVersion.LatestMajor => true,
        _ => v >= LanguageVersion.CSharp8,
    };

    static string NormalizePath(string path) => path.Replace('\\', '/').TrimStart('/');

    static string MakeRelative(string baseDir, string fullPath)
    {
        var sep = System.IO.Path.DirectorySeparatorChar.ToString();
        if (!baseDir.EndsWith(sep)) baseDir += sep;
        return fullPath.StartsWith(baseDir, StringComparison.OrdinalIgnoreCase)
            ? fullPath.Substring(baseDir.Length)
            : fullPath;
    }
}
