using Esolang.Funge.Parser;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Esolang.Funge.Generator;

/// <summary>
/// A source generator that emits method implementations from <c>GenerateFungeMethodAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class MethodGenerator : IIncrementalGenerator
{
    /// <summary>The standard auto-generated file header.</summary>
    public const string CommentAutoGenerated = "// <auto-generated/>";

    /// <summary>The namespace where the generated attribute is placed.</summary>
    public const string NameSpaceName = "Esolang.Funge";

    /// <summary>The generated attribute class name.</summary>
    public const string AttributeName = "GenerateFungeMethodAttribute";

    /// <summary>The source file name used to aggregate generated methods.</summary>
    public const string GeneratedMethodsFileName = "GenerateFungeMethod.g.cs";

    const string GeneratedMethodsFileHeader = $$"""
        {{CommentAutoGenerated}}
        #nullable enable
        #pragma warning disable CS0219
        #pragma warning disable CS1998

        """;

    // -----------------------------------------------------------------------
    // Enumerations for execution signature binding
    // -----------------------------------------------------------------------

    enum ReturnKind
    {
        Void,
        Int,
        String,
        Task,
        TaskInt,
        TaskString,
        ValueTask,
        ValueTaskInt,
        ValueTaskString,
        EnumerableByte,
        AsyncEnumerableByte,
        Invalid,
    }

    enum InputKind { None, String, TextReader, PipeReader }

    enum OutputKind { None, TextWriter, PipeWriter, ReturnString, ReturnEnumerable, ReturnAsyncEnumerable }

    readonly struct ExecutionBinding(
        bool isValid,
        ReturnKind returnKind,
        InputKind inputKind,
        OutputKind outputKind,
        string inputExpression,
        string outputExpression,
        string? cancellationTokenName,
        string? errorId,
        Location? location = null)
    {
        public bool IsValid { get; } = isValid;
        public ReturnKind ReturnKind { get; } = returnKind;
        public InputKind InputKind { get; } = inputKind;
        public OutputKind OutputKind { get; } = outputKind;
        public string InputExpression { get; } = inputExpression;
        public string OutputExpression { get; } = outputExpression;
        public string? CancellationTokenName { get; } = cancellationTokenName;
        public string? ErrorId { get; } = errorId;
        public Location? Location { get; } = location;
        public bool HasExplicitInput => InputKind is not InputKind.None;
        public bool HasExplicitOutput => OutputKind is not OutputKind.None;
    }

    // -----------------------------------------------------------------------
    // IIncrementalGenerator.Initialize
    // -----------------------------------------------------------------------

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("GenerateFungeMethodAttribute.cs", $$"""
                {{CommentAutoGenerated}}
                using System;
                using System.Diagnostics;
                namespace {{NameSpaceName}} {
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                    internal sealed class {{AttributeName}} : Attribute
                    {
                        /// <summary>
                        /// Generate a Funge-98 method implementation from a source file.
                        /// </summary>
                        /// <param name="sourcePath">Path to the Funge-98 source file (.b98). Ignored when <see cref="InlineSource"/> is set.</param>
                        internal {{AttributeName}}(string sourcePath = "") { }
                        /// <summary>
                        /// Inline Funge-98 source code. When non-empty, <c>sourcePath</c> is ignored.
                        /// </summary>
                        public string InlineSource = "";
                    }
                }
                """));

        const string fullAttributeName = NameSpaceName + "." + AttributeName;
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullAttributeName,
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => ctx);

        var generatedTargets = source.Collect();

        var additionalFiles = context.AdditionalTextsProvider
            .Select(static (text, token) => (text.Path, Text: text.GetText(token)?.ToString()))
            .Collect();

        var languageVersion = context.ParseOptionsProvider
            .Select(static (opts, _) =>
                opts is CSharpParseOptions csOpts ? csOpts.LanguageVersion : LanguageVersion.Default);

        var projectDirectory = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
                provider.GlobalOptions.TryGetValue("build_property.MSBuildProjectDirectory", out var dir)
                || provider.GlobalOptions.TryGetValue("build_property.ProjectDir", out dir)
                ? dir : null);

        var inputs = generatedTargets
            .Combine(additionalFiles)
            .Combine(languageVersion)
            .Combine(projectDirectory);

        context.RegisterSourceOutput(inputs, static (ctx, input) =>
        {
            var (((sources, files), langVersion), projDir) = input;

            if (sources.IsDefaultOrEmpty)
                return;

            var methodSb = new StringBuilder(GeneratedMethodsFileHeader);
            var emittedCount = 0;

            foreach (var syntaxCtx in sources)
            {
                var method = (MethodDeclarationSyntax)syntaxCtx.TargetNode;
                var symbol = (IMethodSymbol)syntaxCtx.TargetSymbol;

                if (!IsLanguageVersionAtLeastCSharp8(langVersion))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.LanguageVersionTooLow,
                        method.Identifier.GetLocation(),
                        langVersion.ToDisplayString()));
                }

                // Get sourcePath attribute argument
                var attrData = syntaxCtx.Attributes.FirstOrDefault();
                if (attrData is null) continue;

                var sourcePath = attrData.ConstructorArguments.FirstOrDefault().Value as string;

                // Check for inline source (named argument takes priority over file path)
                string? inlineSource = null;
                foreach (var namedArg in attrData.NamedArguments)
                {
                    if (namedArg.Key == "InlineSource")
                    {
                        inlineSource = namedArg.Value.Value as string;
                        break;
                    }
                }

                if (string.IsNullOrWhiteSpace(inlineSource) && string.IsNullOrWhiteSpace(sourcePath))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InvalidSourcePathParameter,
                        method.Identifier.GetLocation(),
                        symbol.Name));
                    continue;
                }

                // Bind the method signature
                var binding = BindExecutionSignature(symbol, method);
                if (!binding.IsValid)
                {
                    if (binding.ErrorId == DiagnosticDescriptors.InvalidReturnType.Id)
                        ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidReturnType,
                            binding.Location ?? method.Identifier.GetLocation(),
                            symbol.ReturnType.ToDisplayString()));
                    else if (binding.ErrorId == DiagnosticDescriptors.DuplicateParameter.Id)
                        ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.DuplicateParameter,
                            binding.Location ?? method.Identifier.GetLocation(),
                            symbol.Name, symbol.Name));
                    else if (binding.ErrorId == DiagnosticDescriptors.ReturnOutputConflict.Id)
                        ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.ReturnOutputConflict,
                            binding.Location ?? method.Identifier.GetLocation(),
                            symbol.Name));
                    else
                        ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidParameter,
                            binding.Location ?? method.Identifier.GetLocation(),
                            symbol.Name));
                    continue;
                }

                // Resolve source text: inline takes priority over file
                string? sourceText = null;
                if (!string.IsNullOrWhiteSpace(inlineSource))
                {
                    sourceText = inlineSource;
                }
                else
                {
                    foreach (var (filePath, fileText) in files)
                    {
                        if (filePath is null || fileText is null) continue;
                        var normalizedSource = NormalizePath(sourcePath!);
                        var normalizedFile = NormalizePath(filePath);
                        // Strip the ".funge.txt" intermediate suffix that the .targets file appends
                        const string fungeSuffix = ".funge.txt";
                        var compareFile = normalizedFile.EndsWith(fungeSuffix, StringComparison.OrdinalIgnoreCase)
                            ? normalizedFile.Substring(0, normalizedFile.Length - fungeSuffix.Length)
                            : normalizedFile;
                        if (string.Equals(compareFile, normalizedSource, StringComparison.OrdinalIgnoreCase)
                            || compareFile.EndsWith("/" + normalizedSource, StringComparison.OrdinalIgnoreCase)
                            || string.Equals(System.IO.Path.GetFileName(compareFile),
                                   System.IO.Path.GetFileName(normalizedSource), StringComparison.OrdinalIgnoreCase))
                        {
                            sourceText = fileText;
                            break;
                        }
                    }

                    if (sourceText is null)
                    {
                        ctx.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticDescriptors.SourceFileNotFound,
                            method.Identifier.GetLocation(),
                            sourcePath));
                        continue;
                    }
                }

                // Parse the Funge space
                var space = FungeParser.Parse(sourceText!);

                // Scan for I/O usage
                var (usesOutput, usesInput) = ScanFungeIo(space);

                if (usesOutput && !binding.HasExplicitOutput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.RequiredOutputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                if (usesInput && !binding.HasExplicitInput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.RequiredInputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                if (!usesInput && binding.HasExplicitInput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.UnusedInputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                var displayPath = !string.IsNullOrWhiteSpace(inlineSource) ? "<inline>" : sourcePath!;
                var emitted = EmitMethod(symbol, method, space, binding, projDir, displayPath);
                methodSb.AppendLine(emitted);
                emittedCount++;
            }

            if (emittedCount > 0)
                ctx.AddSource(GeneratedMethodsFileName, methodSb.ToString());

            EmitRuntimeIfNeeded(ctx, emittedCount > 0);
        });
    }

    // -----------------------------------------------------------------------
    // Signature binding
    // -----------------------------------------------------------------------

    static ExecutionBinding BindExecutionSignature(IMethodSymbol method, MethodDeclarationSyntax syntax)
    {
        var returnKind = method.ReturnType switch
        {
            { SpecialType: SpecialType.System_Void } => ReturnKind.Void,
            { SpecialType: SpecialType.System_Int32 } => ReturnKind.Int,
            { Name: "String", ContainingNamespace.Name: "System" } => ReturnKind.String,
            INamedTypeSymbol t when t.Name == "Task" && t.TypeArguments.Length == 0
                => ReturnKind.Task,
            INamedTypeSymbol t when t.Name == "Task" && t.TypeArguments.Length == 1
                && t.TypeArguments[0].SpecialType == SpecialType.System_Int32
                => ReturnKind.TaskInt,
            INamedTypeSymbol t when t.Name == "Task" && t.TypeArguments.Length == 1
                && t.TypeArguments[0].SpecialType == SpecialType.System_String
                => ReturnKind.TaskString,
            INamedTypeSymbol t when t.Name == "ValueTask" && t.TypeArguments.Length == 0
                => ReturnKind.ValueTask,
            INamedTypeSymbol t when t.Name == "ValueTask" && t.TypeArguments.Length == 1
                && t.TypeArguments[0].SpecialType == SpecialType.System_Int32
                => ReturnKind.ValueTaskInt,
            INamedTypeSymbol t when t.Name == "ValueTask" && t.TypeArguments.Length == 1
                && t.TypeArguments[0].SpecialType == SpecialType.System_String
                => ReturnKind.ValueTaskString,
            INamedTypeSymbol t when t.Name == "IEnumerable" && t.TypeArguments.Length == 1
                && t.TypeArguments[0].SpecialType == SpecialType.System_Byte
                => ReturnKind.EnumerableByte,
            INamedTypeSymbol t when t.Name == "IAsyncEnumerable" && t.TypeArguments.Length == 1
                && t.TypeArguments[0].SpecialType == SpecialType.System_Byte
                => ReturnKind.AsyncEnumerableByte,
            _ => ReturnKind.Invalid,
        };

        if (returnKind == ReturnKind.Invalid)
            return new(false, returnKind, InputKind.None, OutputKind.None, "", "", null,
                DiagnosticDescriptors.InvalidReturnType.Id);

        var outputKind = returnKind switch
        {
            ReturnKind.String or ReturnKind.TaskString or ReturnKind.ValueTaskString
                => OutputKind.ReturnString,
            ReturnKind.EnumerableByte => OutputKind.ReturnEnumerable,
            ReturnKind.AsyncEnumerableByte => OutputKind.ReturnAsyncEnumerable,
            _ => OutputKind.None,
        };

        var inputKind = InputKind.None;
        var inputExpr = "";
        var outputExpr = "";
        string? cancellationTokenName = null;
        var hasCancellationToken = false;

        foreach (var p in method.Parameters)
        {
            if (p.RefKind is not RefKind.None)
                return new(false, returnKind, inputKind, outputKind, "", "", null,
                    DiagnosticDescriptors.InvalidParameter.Id, p.Locations.FirstOrDefault());

            if (p.Type.SpecialType == SpecialType.System_String)
            {
                if (inputKind is not InputKind.None)
                    return new(false, returnKind, inputKind, outputKind, "", "", null,
                        DiagnosticDescriptors.DuplicateParameter.Id, p.Locations.FirstOrDefault());
                inputKind = InputKind.String;
                inputExpr = p.Name;
                continue;
            }

            var typeName = p.Type.ToDisplayString();

            if (typeName == "System.IO.TextReader")
            {
                if (inputKind is not InputKind.None)
                    return new(false, returnKind, inputKind, outputKind, "", "", null,
                        DiagnosticDescriptors.DuplicateParameter.Id, p.Locations.FirstOrDefault());
                inputKind = InputKind.TextReader;
                inputExpr = p.Name;
                continue;
            }

            if (typeName == "System.IO.Pipelines.PipeReader")
            {
                if (inputKind is not InputKind.None)
                    return new(false, returnKind, inputKind, outputKind, "", "", null,
                        DiagnosticDescriptors.DuplicateParameter.Id, p.Locations.FirstOrDefault());
                inputKind = InputKind.PipeReader;
                inputExpr = p.Name;
                continue;
            }

            if (typeName == "System.IO.TextWriter")
            {
                if (returnKind is not ReturnKind.Void)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, p.Name,
                        cancellationTokenName, DiagnosticDescriptors.ReturnOutputConflict.Id,
                        p.Locations.FirstOrDefault());
                if (outputKind is not OutputKind.None)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, p.Name,
                        cancellationTokenName, DiagnosticDescriptors.DuplicateParameter.Id,
                        p.Locations.FirstOrDefault());
                outputKind = OutputKind.TextWriter;
                outputExpr = p.Name;
                continue;
            }

            if (typeName == "System.IO.Pipelines.PipeWriter")
            {
                if (returnKind is not ReturnKind.Void)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, p.Name,
                        cancellationTokenName, DiagnosticDescriptors.ReturnOutputConflict.Id,
                        p.Locations.FirstOrDefault());
                if (outputKind is not OutputKind.None)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, p.Name,
                        cancellationTokenName, DiagnosticDescriptors.DuplicateParameter.Id,
                        p.Locations.FirstOrDefault());
                outputKind = OutputKind.PipeWriter;
                outputExpr = p.Name;
                continue;
            }

            if (typeName == "System.Threading.CancellationToken")
            {
                if (hasCancellationToken)
                    return new(false, returnKind, inputKind, outputKind, inputExpr, outputExpr,
                        cancellationTokenName, DiagnosticDescriptors.DuplicateParameter.Id,
                        p.Locations.FirstOrDefault());
                hasCancellationToken = true;
                cancellationTokenName = p.Name;
                continue;
            }

            return new(false, returnKind, inputKind, outputKind, inputExpr, outputExpr,
                cancellationTokenName, DiagnosticDescriptors.InvalidParameter.Id,
                p.Locations.FirstOrDefault());
        }

        return new(true, returnKind, inputKind, outputKind, inputExpr, outputExpr, cancellationTokenName, null);
    }

    // -----------------------------------------------------------------------
    // Method emit
    // -----------------------------------------------------------------------

    static string EmitMethod(
        IMethodSymbol symbol,
        MethodDeclarationSyntax syntax,
        FungeSpace space,
        ExecutionBinding binding,
        string? projDir,
        string sourcePath)
    {
        var ns = symbol.ContainingType.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingType.ContainingNamespace.ToDisplayString() : null;

        var typeKeyword = symbol.ContainingType.TypeKind switch
        {
            TypeKind.Struct when symbol.ContainingType.IsRecord => "record struct",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            TypeKind.Class when symbol.ContainingType.IsRecord => "record",
            _ => "class",
        };

        var typeName = symbol.ContainingType.Name;
        var accessibility = GetAccessibility(symbol.DeclaredAccessibility);
        var staticMod = symbol.IsStatic ? " static" : string.Empty;
        var asyncMod = binding.ReturnKind == ReturnKind.AsyncEnumerableByte ? " async" : string.Empty;
        var returnTypeSyntax = symbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var paramList = string.Join(", ", System.Linq.Enumerable.Select(symbol.Parameters, p =>
        {
            var prefix = (binding.ReturnKind == ReturnKind.AsyncEnumerableByte
                && binding.CancellationTokenName is not null
                && string.Equals(p.Name, binding.CancellationTokenName, StringComparison.Ordinal))
                ? "[global::System.Runtime.CompilerServices.EnumeratorCancellation] "
                : string.Empty;
            return prefix + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + " " + p.Name;
        }));

        var relPath = projDir is not null ? MakeRelative(projDir, sourcePath) : sourcePath;
        var sb = new StringBuilder();

        if (ns is not null) { sb.Append("namespace ").Append(ns).AppendLine(" {").AppendLine(); }
        sb.Append("partial ").Append(typeKeyword).Append(' ').AppendLine(typeName);
        sb.AppendLine("{");
        sb.AppendLine($"    // Generated from: {relPath}");
        sb.Append("    ").Append(accessibility).Append(staticMod).Append(asyncMod)
            .Append(" partial ").Append(returnTypeSyntax).Append(' ')
            .Append(symbol.Name).Append('(').Append(paramList).AppendLine(")");
        sb.AppendLine("    {");

        EmitBody(sb, space, binding);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        if (ns is not null) sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitBody(StringBuilder sb, FungeSpace space, ExecutionBinding binding)
    {
        var inputExpr = binding.InputKind switch
        {
            InputKind.None => "global::System.IO.TextReader.Null",
            InputKind.String =>
                $"new global::System.IO.StringReader({binding.InputExpression} ?? string.Empty)",
            InputKind.TextReader => binding.InputExpression,
            InputKind.PipeReader =>
                $"new global::System.IO.StreamReader({binding.InputExpression}.AsStream())",
            _ => "global::System.IO.TextReader.Null",
        };
        var cancellationTokenExpr = binding.CancellationTokenName is null
            ? "global::System.Threading.CancellationToken.None"
            : binding.CancellationTokenName;

        EmitSpaceData(sb, space);

        switch (binding.ReturnKind)
        {
            case ReturnKind.Void:
                {
                    if (binding.OutputKind == OutputKind.PipeWriter)
                    {
                        sb.AppendLine($"        using var __fungeOutput = new global::System.IO.StreamWriter({binding.OutputExpression}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);");
                        sb.AppendLine("        global::Esolang.Funge.__Generated.FungeRuntime.RunSync(");
                        sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == OutputKind.TextWriter
                            ? binding.OutputExpression
                            : "global::System.IO.TextWriter.Null";
                        sb.AppendLine("        global::Esolang.Funge.__Generated.FungeRuntime.RunSync(");
                        sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                    }
                    break;
                }

            case ReturnKind.Int:
                sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunSync(");
                sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, global::System.IO.TextWriter.Null, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                break;

            case ReturnKind.String:
                sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunString(");
                sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                break;

            case ReturnKind.Task:
                {
                    if (binding.OutputKind == OutputKind.PipeWriter)
                    {
                        sb.AppendLine($"        using var __fungeOutput = new global::System.IO.StreamWriter({binding.OutputExpression}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);");
                        sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunTask(");
                        sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == OutputKind.TextWriter
                            ? binding.OutputExpression
                            : "global::System.IO.TextWriter.Null";
                        sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunTask(");
                        sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                    }
                    break;
                }

            case ReturnKind.TaskInt:
                sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunTaskInt(");
                sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                break;

            case ReturnKind.TaskString:
                sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunTaskString(");
                sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                break;

            case ReturnKind.ValueTask:
                {
                    if (binding.OutputKind == OutputKind.PipeWriter)
                    {
                        sb.AppendLine($"        using var __fungeOutput = new global::System.IO.StreamWriter({binding.OutputExpression}.AsStream(), global::System.Text.Encoding.UTF8, 1024, leaveOpen: true);");
                        sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunValueTask(");
                        sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == OutputKind.TextWriter
                            ? binding.OutputExpression
                            : "global::System.IO.TextWriter.Null";
                        sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunValueTask(");
                        sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                    }
                    break;
                }

            case ReturnKind.ValueTaskInt:
                sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunValueTaskInt(");
                sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                break;

            case ReturnKind.ValueTaskString:
                sb.AppendLine("        return global::Esolang.Funge.__Generated.FungeRuntime.RunValueTaskString(");
                sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr});");
                break;

            case ReturnKind.EnumerableByte:
                sb.AppendLine("        foreach (var __b in global::Esolang.Funge.__Generated.FungeRuntime.RunEnumerable(");
                sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}))");
                sb.AppendLine("            yield return __b;");
                break;

            case ReturnKind.AsyncEnumerableByte:
                sb.AppendLine("        await foreach (var __b in global::Esolang.Funge.__Generated.FungeRuntime.RunAsyncEnumerable(");
                sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}))");
                sb.AppendLine("            yield return __b;");
                break;
        }
    }

    static void EmitRuntimeRunCall(StringBuilder sb, string inputExpr, string outputExpr, bool hasInput, bool hasOutput)
    {
        sb.AppendLine("        global::Esolang.Funge.__Generated.FungeRuntime.Run(");
        sb.AppendLine($"            __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outputExpr}, {(hasInput ? "true" : "false")}, {(hasOutput ? "true" : "false")});");
    }

    static void EmitSpaceData(StringBuilder sb, FungeSpace space)
    {
        sb.AppendLine($"        int __minX = {space.MinX}, __minY = {space.MinY}, __minZ = {space.MinZ}, __maxX = {space.MaxX}, __maxY = {space.MaxY}, __maxZ = {space.MaxZ};");
        sb.AppendLine("        var __cells = new global::System.Collections.Generic.Dictionary<(int, int, int), int>();");
        for (var z = space.MinZ; z <= space.MaxZ; z++)
            for (var y = space.MinY; y <= space.MaxY; y++)
                for (var x = space.MinX; x <= space.MaxX; x++)
                {
                    var val = space[new FungeVector(x, y, z)];
                    if (val != ' ')
                        sb.AppendLine($"        __cells[({x}, {y}, {z})] = {val};");
                }
    }

    // -----------------------------------------------------------------------
    // I/O scan
    // -----------------------------------------------------------------------

    static (bool usesOutput, bool usesInput) ScanFungeIo(FungeSpace space)
    {
        bool usesOutput = false, usesInput = false;
        for (var z = space.MinZ; z <= space.MaxZ; z++)
            for (var y = space.MinY; y <= space.MaxY; y++)
                for (var x = space.MinX; x <= space.MaxX; x++)
                {
                    var c = space[new FungeVector(x, y, z)];
                    if (c is '.' or ',') usesOutput = true;
                    if (c is '&' or '~') usesInput = true;
                    if (usesOutput && usesInput) return (true, true);
                }
        return (usesOutput, usesInput);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Protected => "protected",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => string.Empty,
    };

    static bool IsLanguageVersionAtLeastCSharp8(LanguageVersion v) => v switch
    {
        LanguageVersion.Default => true,
        LanguageVersion.Latest => true,
        LanguageVersion.Preview => true,
        LanguageVersion.LatestMajor => true,
        _ => v >= LanguageVersion.CSharp8,
    };

    static string NormalizePath(string path) => path.Replace('\\', '/').TrimStart('/');

    static string MakeRelative(string baseDir, string fullPath)
    {
        var sep = System.IO.Path.DirectorySeparatorChar.ToString();
        if (!baseDir.EndsWith(sep)) baseDir += sep;
        return fullPath.StartsWith(baseDir, StringComparison.OrdinalIgnoreCase)
            ? fullPath.Substring(baseDir.Length)
            : fullPath;
    }
}
