using System.Text;

namespace Esolang.Funge.Generator;

partial class MethodGenerator
{
    const string FungeRuntimeFileName = "FungeRuntime.g.cs";

    static void EmitRuntimeIfNeeded(Microsoft.CodeAnalysis.SourceProductionContext ctx, bool needed)
    {
        if (!needed) return;
        ctx.AddSource(FungeRuntimeFileName, BuildRuntimeSource());
    }

    static string BuildRuntimeSource() => """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS1591
        using System;
        using System.Collections.Generic;
        using System.IO;

        namespace Esolang.Funge.__Generated
        {
            internal static class FungeRuntime
            {
                internal static int Run(
                    Dictionary<(int, int, int), int> cells,
                    int minX, int minY, int minZ, int maxX, int maxY, int maxZ,
                    TextReader input,
                    TextWriter output,
                    bool hasInput,
                    bool hasOutput)
                {
                    int px = 0, py = 0, pz = 0, dx = 1, dy = 0, dz = 0;
                    bool stringMode = false;
                    var stack = new List<int>();
                    var rng = new Random();
                    int exitCode = 0;

                    int GetCell(int x, int y, int z) => cells.TryGetValue((x, y, z), out var v) ? v : ' ';
                    void SetCell(int x, int y, int z, int val)
                    {
                        if (val == ' ') cells.Remove((x, y, z));
                        else cells[(x, y, z)] = val;
                    }
                    int Pop() { if (stack.Count == 0) return 0; var v = stack[stack.Count - 1]; stack.RemoveAt(stack.Count - 1); return v; }
                    void Push(int v) => stack.Add(v);

                    (int nx, int ny, int nz) Advance(int x, int y, int z, int ddx, int ddy, int ddz)
                    {
                        if (maxX < minX) return (x, y, z);
                        int nx = x + ddx, ny = y + ddy, nz = z + ddz;
                        int w = maxX - minX + 1, h = maxY - minY + 1, d = maxZ - minZ + 1;
                        if (nx < minX) nx = maxX - ((minX - nx - 1) % w);
                        else if (nx > maxX) nx = minX + ((nx - maxX - 1) % w);
                        if (ny < minY) ny = maxY - ((minY - ny - 1) % h);
                        else if (ny > maxY) ny = minY + ((ny - maxY - 1) % h);
                        if (nz < minZ) nz = maxZ - ((minZ - nz - 1) % d);
                        else if (nz > maxZ) nz = minZ + ((nz - maxZ - 1) % d);
                        return (nx, ny, nz);
                    }

                    bool IsSgmlSpace(int c) => c is ' ' or '\t' or '\f' or '\v';

                    bool stopped = false;

                    void ExecuteInstruction(int cell, ref bool suppressAdvance)
                    {
                        switch (cell)
                        {
                            case ' ': case '\t': case '\f': case '\v': case 'z': break;
                            case '!': Push(Pop() == 0 ? 1 : 0); break;
                            case '$': Pop(); break;
                            case ':': { int v = Pop(); Push(v); Push(v); break; }
                            case '\\': { int b = Pop(), a = Pop(); Push(b); Push(a); break; }
                            case 'n': stack.Clear(); break;
                            case '+': { int b = Pop(), a = Pop(); Push(a + b); break; }
                            case '-': { int b = Pop(), a = Pop(); Push(a - b); break; }
                            case '*': { int b = Pop(), a = Pop(); Push(a * b); break; }
                            case '/': { int b = Pop(), a = Pop(); Push(b == 0 ? 0 : a / b); break; }
                            case '%': { int b = Pop(), a = Pop(); Push(b == 0 ? 0 : a % b); break; }
                            case '`': { int b = Pop(), a = Pop(); Push(a > b ? 1 : 0); break; }
                            case '0': case '1': case '2': case '3': case '4':
                            case '5': case '6': case '7': case '8': case '9': Push(cell - '0'); break;
                            case 'a': Push(10); break; case 'b': Push(11); break; case 'c': Push(12); break;
                            case 'd': Push(13); break; case 'e': Push(14); break; case 'f': Push(15); break;
                            case '>': dx = 1; dy = 0; dz = 0; break;
                            case '<': dx = -1; dy = 0; dz = 0; break;
                            case '^': dx = 0; dy = -1; dz = 0; break;
                            case 'v': dx = 0; dy = 1; dz = 0; break;
                            case 'h': dx = 0; dy = 0; dz = -1; break;
                            case 'l': dx = 0; dy = 0; dz = 1; break;
                            case '?':
                                switch (rng.Next(6))
                                {
                                    case 0: dx=1;dy=0;dz=0;break;
                                    case 1: dx=-1;dy=0;dz=0;break;
                                    case 2: dx=0;dy=-1;dz=0;break;
                                    case 3: dx=0;dy=1;dz=0;break;
                                    case 4: dx=0;dy=0;dz=-1;break;
                                    default: dx=0;dy=0;dz=1;break;
                                }
                                break;
                            case 'm': { int v = Pop(); dx = 0; dy = 0; dz = v == 0 ? 1 : -1; break; }
                            case '_': { int v = Pop(); dx = v == 0 ? 1 : -1; dy = 0; dz = 0; break; }
                            case '|': { int v = Pop(); dy = v == 0 ? 1 : -1; dx = 0; dz = 0; break; }
                            case '[': { int ndx = dy, ndy = -dx; dx = ndx; dy = ndy; dz = 0; break; }
                            case ']': { int ndx = -dy, ndy = dx; dx = ndx; dy = ndy; dz = 0; break; }
                            case 'r': dx = -dx; dy = -dy; dz = -dz; break;
                            case 'x': { int ndz = Pop(), ndy = Pop(), ndx = Pop(); dx = ndx; dy = ndy; dz = ndz; break; }
                            case 'w': { int b = Pop(), a = Pop(); if(a>b){int ndx=-dy,ndy=dx;dx=ndx;dy=ndy;dz=0;}else if(a<b){int ndx=dy,ndy=-dx;dx=ndx;dy=ndy;dz=0;} break; }
                            case '#': (px, py, pz) = Advance(px, py, pz, dx, dy, dz); break;
                            case 'j':
                            {
                                int s = Pop(); int jdx = s >= 0 ? dx : -dx, jdy = s >= 0 ? dy : -dy, jdz = s >= 0 ? dz : -dz, abs = s < 0 ? -s : s;
                                for (int i = 0; i < abs; i++) (px, py, pz) = Advance(px, py, pz, jdx, jdy, jdz);
                                suppressAdvance = true; break;
                            }
                            case ';':
                                (px, py, pz) = Advance(px, py, pz, dx, dy, dz);
                                while (GetCell(px, py, pz) != ';') (px, py, pz) = Advance(px, py, pz, dx, dy, dz);
                                break;
                            case '\'': (px, py, pz) = Advance(px, py, pz, dx, dy, dz); Push(GetCell(px, py, pz)); break;
                            case 's': { int sv = Pop(); (px, py, pz) = Advance(px, py, pz, dx, dy, dz); SetCell(px, py, pz, sv); break; }
                            case '"': stringMode = true; break;
                            case 'g': { int gz = Pop(), gy = Pop(), gx = Pop(); Push(GetCell(gx, gy, gz)); break; }
                            case 'p': { int gz = Pop(), gy = Pop(), gx = Pop(), pv = Pop(); SetCell(gx, gy, gz, pv); break; }
                            case '.':
                                if (!hasOutput) throw new InvalidOperationException("Funge output instruction '.' executed without an output interface.");
                                output.Write(Pop()); output.Write(' '); break;
                            case ',':
                                if (!hasOutput) throw new InvalidOperationException("Funge output instruction ',' executed without an output interface.");
                                output.Write((char)Pop()); break;
                            case '&':
                            {
                                if (!hasInput) throw new InvalidOperationException("Funge input instruction '&' executed without an input interface.");
                                var line = input.ReadLine(); if(line==null){dx=-dx;dy=-dy;dz=-dz;}else Push(int.TryParse(line.Trim(),out int iv)?iv:0); break;
                            }
                            case '~':
                            {
                                if (!hasInput) throw new InvalidOperationException("Funge input instruction '~' executed without an input interface.");
                                int ch = input.Read(); if(ch<0){dx=-dx;dy=-dy;dz=-dz;}else Push(ch); break;
                            }
                            case 'k':
                            {
                                int n = Pop();
                                var (ix, iy, iz) = Advance(px, py, pz, dx, dy, dz);
                                while (true)
                                {
                                    int c = GetCell(ix, iy, iz);
                                    if (IsSgmlSpace(c))
                                    {
                                        (ix, iy, iz) = Advance(ix, iy, iz, dx, dy, dz);
                                    }
                                    else if (c == ';')
                                    {
                                        (ix, iy, iz) = Advance(ix, iy, iz, dx, dy, dz);
                                        while (GetCell(ix, iy, iz) != ';') (ix, iy, iz) = Advance(ix, iy, iz, dx, dy, dz);
                                        (ix, iy, iz) = Advance(ix, iy, iz, dx, dy, dz);
                                    }
                                    else
                                    {
                                        break;
                                    }
                                }

                                if (n == 0)
                                {
                                    (px, py, pz) = (ix, iy, iz);
                                }
                                else
                                {
                                    int operand = GetCell(ix, iy, iz);
                                    for (int i = 0; i < n && !stopped; i++)
                                    {
                                        bool dummy = false;
                                        ExecuteInstruction(operand, ref dummy);
                                    }
                                }
                                break;
                            }
                            case '@': stopped = true; break;
                            case 'q': exitCode = Pop(); stopped = true; break;
                            default: if (cell >= 'A' && cell <= 'Z') { dx = -dx; dy = -dy; dz = -dz; } break;
                        }
                    }

                    while (!stopped)
                    {
                        int cell = GetCell(px, py, pz);
                        if (stringMode)
                        {
                            if (cell == '"')
                            {
                                stringMode = false;
                            }
                            else if (IsSgmlSpace(cell))
                            {
                                Push(' ');
                                while (true)
                                {
                                    var (nx, ny, nz) = Advance(px, py, pz, dx, dy, dz);
                                    if (IsSgmlSpace(GetCell(nx, ny, nz)))
                                    {
                                        (px, py, pz) = (nx, ny, nz);
                                    }
                                    else
                                    {
                                        break;
                                    }
                                }
                            }
                            else
                            {
                                Push(cell);
                            }
                            (px, py, pz) = Advance(px, py, pz, dx, dy, dz);
                            continue;
                        }

                        bool suppressAdvance = false;
                        ExecuteInstruction(cell, ref suppressAdvance);
                        if (!stopped && !suppressAdvance) (px, py, pz) = Advance(px, py, pz, dx, dy, dz);
                    }

                    return exitCode;
                }
            }
        }
        """;
}
