using Esolang.Funge.Parser;
using Esolang.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;
using static Esolang.Generator.BindingError;

namespace Esolang.Funge.Generator;

/// <summary>
/// A source generator that emits method implementations from <c>GenerateFungeMethodAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class MethodGenerator : IIncrementalGenerator
{
    /// <summary>The standard auto-generated file header.</summary>
    public const string CommentAutoGenerated = "// <auto-generated/>";

    /// <summary>The namespace where the generated attribute is placed.</summary>
    public const string NameSpaceName = "Esolang.Funge";

    /// <summary>The generated attribute class name.</summary>
    public const string AttributeName = "GenerateFungeMethodAttribute";

    /// <summary>The source file name used to aggregate generated methods.</summary>
    public const string GeneratedMethodsFileName = "GenerateFungeMethod.g.cs";

    const string GeneratedMethodsFileHeader = $$"""
        {{CommentAutoGenerated}}
        #nullable enable
        #pragma warning disable CS0219
        #pragma warning disable CS1998
        using System.Linq;
        """;

    readonly record struct FungeExecutionBinding(
        MethodSignatureBinding Binding,
        string? ArgsExpression = null,
        string? EnvsExpression = null,
        string? FingerprintsExpression = null,
        BindingError? FungeError = null)
    {
        [System.Diagnostics.CodeAnalysis.MemberNotNullWhen(false, nameof(FungeError))]
        public bool IsValid => Binding.IsValid && FungeError is null;
    }

    // -----------------------------------------------------------------------
    // IIncrementalGenerator.Initialize
    // -----------------------------------------------------------------------

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("GenerateFungeMethodAttribute.cs", $$"""
                {{CommentAutoGenerated}}
                using System;
                using System.Diagnostics;
                namespace {{NameSpaceName}} {
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                    internal sealed class {{AttributeName}} : Attribute
                    {
                        /// <summary>
                        /// Generate a Funge-98 method implementation from a source file.
                        /// </summary>
                        /// <param name="sourcePath">Path to the Funge-98 source file (.b98). Ignored when <see cref="InlineSource"/> is set.</param>
                        internal {{AttributeName}}(string sourcePath = "") { }
                        /// <summary>
                        /// Inline Funge-98 source code. When non-empty, <c>sourcePath</c> is ignored.
                        /// </summary>
                        public string InlineSource = "";
                        /// <summary>
                        /// Name of a method or property on the containing type that returns
                        /// <see cref="System.Collections.Generic.IEnumerable{T}"/> of <c>Esolang.Funge.IFingerprint</c>
                        /// instances to register with the runtime.
                        /// </summary>
                        public string FingerprintsProvider = "";
                    }
                }
                """));

        const string fullAttributeName = NameSpaceName + "." + AttributeName;
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullAttributeName,
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => ctx);

        var generatedTargets = source.Collect();

        var additionalFiles = context.AdditionalTextsProvider
            .Select(static (text, token) => (text.Path, Text: text.GetText(token)?.ToString()))
            .Collect();

        var languageVersion = context.ParseOptionsProvider
            .Select(static (opts, _) =>
                opts is CSharpParseOptions csOpts ? csOpts.LanguageVersion : LanguageVersion.Default);

        var projectDirectory = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
                provider.GlobalOptions.TryGetValue("build_property.MSBuildProjectDirectory", out var dir)
                || provider.GlobalOptions.TryGetValue("build_property.ProjectDir", out dir)
                ? dir : null);

        var compilation = context.CompilationProvider;
        var knownTypes = compilation.Select(static (c, _) => new KnownTypes(c));
        var knownFungeTypes = compilation.Select(static (c, _) => new KnownFungeTypes(c));

        var inputs = generatedTargets
            .Combine(additionalFiles)
            .Combine(languageVersion)
            .Combine(projectDirectory)
            .Combine(compilation)
            .Combine(knownTypes)
            .Combine(knownFungeTypes);

        context.RegisterSourceOutput(inputs, static (ctx, input) =>
        {
            var ((((((sources, files), langVersion), projDir), compilation), types), fungeTypes) = input;

            if (sources.IsDefaultOrEmpty)
                return;

            var methodSb = new StringBuilder(GeneratedMethodsFileHeader);
            var emittedCount = 0;
            var runtimeFeatures = RuntimeFacadeFeatures.None;

            foreach (var syntaxCtx in sources)
            {
                ctx.CancellationToken.ThrowIfCancellationRequested();
                var method = (MethodDeclarationSyntax)syntaxCtx.TargetNode;
                var symbol = (IMethodSymbol)syntaxCtx.TargetSymbol;

                if (!symbol.IsPartialDefinition)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.MethodMustBePartial,
                        method.Identifier.GetLocation(),
                        symbol.Name));
                    continue;
                }

                if (!IsLanguageVersionAtLeastCSharp8(langVersion))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.LanguageVersionTooLow,
                        method.Identifier.GetLocation(),
                        langVersion.ToDisplayString()));
                }

                // Get sourcePath attribute argument
                var attrData = syntaxCtx.Attributes.FirstOrDefault();
                if (attrData is null) continue;

                string? sourcePath = null;
                if (attrData.ConstructorArguments.Length > 0)
                {
                    sourcePath = attrData.ConstructorArguments[0].Value as string;
                }
                else
                {
                    // Fallback to syntax if semantic model couldn't resolve
                    var attributeSyntax = attrData.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
                    if (attributeSyntax?.ArgumentList?.Arguments.Count > 0)
                    {
                        var arg = attributeSyntax.ArgumentList.Arguments[0].Expression;
                        if (arg is LiteralExpressionSyntax lit)
                        {
                            sourcePath = lit.Token.ValueText;
                        }
                    }
                }

                // Check for inline source (named argument takes priority over file path)
                string? inlineSource = null;
                string? fingerprintsProviderName = null;
                foreach (var namedArg in attrData.NamedArguments)
                {
                    if (namedArg.Key == "InlineSource")
                        inlineSource = namedArg.Value.Value as string;
                    else if (namedArg.Key == "FingerprintsProvider")
                        fingerprintsProviderName = namedArg.Value.Value as string;
                }

                if (inlineSource == null || fingerprintsProviderName == null)
                {
                    var attributeSyntax = attrData.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
                    if (attributeSyntax?.ArgumentList != null)
                    {
                        foreach (var arg in attributeSyntax.ArgumentList.Arguments)
                        {
                            if (arg.NameEquals?.Name.Identifier.ValueText == "InlineSource"
                                && arg.Expression is LiteralExpressionSyntax lit1)
                            {
                                inlineSource ??= lit1.Token.ValueText;
                            }
                            else if (arg.NameEquals?.Name.Identifier.ValueText == "FingerprintsProvider"
                                && arg.Expression is LiteralExpressionSyntax lit2)
                            {
                                fingerprintsProviderName ??= lit2.Token.ValueText;
                            }
                        }
                    }
                }

                if (string.IsNullOrWhiteSpace(inlineSource) && string.IsNullOrWhiteSpace(sourcePath))
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InvalidSourcePathParameter,
                        method.Identifier.GetLocation(),
                        symbol.Name));
                    continue;
                }

                ctx.CancellationToken.ThrowIfCancellationRequested();
                // Bind the method signature
                var binding = BindExecutionSignature(symbol, compilation, types, fungeTypes, fingerprintsProviderName, symbol, ctx);
                if (!binding.IsValid)
                {
                    var error = binding.FungeError ?? binding.Binding.Error!;
                    var location = error.Location ?? method.Identifier.GetLocation();

                    var descriptor = error switch
                    {
                        UnsupportedReturnType => DiagnosticDescriptors.InvalidReturnType,
                        DuplicateInput or DuplicateOutput or DuplicateCancellationToken or DuplicateLogger => DiagnosticDescriptors.DuplicateParameter,
                        ReturnOutputConflict => DiagnosticDescriptors.ReturnOutputConflict,
                        _ => DiagnosticDescriptors.InvalidParameter,
                    };

                    var messageArgs = error switch
                    {
                        UnsupportedReturnType e => new object[] { e.ReturnType.ToDisplayString() },
                        DuplicateInput e => [e.Parameter.Type.ToDisplayString(), symbol.Name],
                        DuplicateOutput e => [e.Parameter.Type.ToDisplayString(), symbol.Name],
                        DuplicateCancellationToken e => [e.Parameter.Type.ToDisplayString(), symbol.Name],
                        DuplicateLogger e => [e.Parameter.Type.ToDisplayString(), symbol.Name],
                        ReturnOutputConflict e => [symbol.Name],
                        InvalidParameterModifier e => [e.Parameter.Name],
                        _ => [symbol.Name]
                    };

                    ctx.ReportDiagnostic(Diagnostic.Create(descriptor, location, messageArgs));
                    continue;
                }

                // Resolve source text: inline takes priority over file
                string? sourceText = null;
                if (!string.IsNullOrWhiteSpace(inlineSource))
                {
                    sourceText = inlineSource;
                }
                else
                {
                    foreach (var (filePath, fileText) in files)
                    {
                        ctx.CancellationToken.ThrowIfCancellationRequested();
                        if (filePath is null || fileText is null) continue;
                        var normalizedSource = NormalizePath(sourcePath!);
                        var normalizedFile = NormalizePath(filePath);
                        // Strip the ".funge.txt" intermediate suffix that the .targets file appends
                        const string fungeSuffix = ".funge.txt";
                        var compareFile = normalizedFile.EndsWith(fungeSuffix, StringComparison.OrdinalIgnoreCase)
                            ? normalizedFile[..^fungeSuffix.Length]
                            : normalizedFile;
                        if (string.Equals(compareFile, normalizedSource, StringComparison.OrdinalIgnoreCase)
                            || compareFile.EndsWith("/" + normalizedSource, StringComparison.OrdinalIgnoreCase)
                            || string.Equals(Path.GetFileName(compareFile),
                                   Path.GetFileName(normalizedSource), StringComparison.OrdinalIgnoreCase))
                        {
                            sourceText = fileText;
                            break;
                        }
                    }

                    if (sourceText is null)
                    {
                        ctx.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticDescriptors.SourceFileNotFound,
                            method.Identifier.GetLocation(),
                            sourcePath));
                        continue;
                    }
                }

                // Parse the Funge space
                ctx.CancellationToken.ThrowIfCancellationRequested();
                var space = FungeParser.Parse(sourceText!, ctx.CancellationToken);
                ctx.CancellationToken.ThrowIfCancellationRequested();

                // Scan for I/O usage
                var (usesOutput, usesInput) = ScanFungeIo(space, ctx.CancellationToken);

                if (usesOutput && !binding.Binding.HasExplicitOutput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.RequiredOutputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                if (usesInput && !binding.Binding.HasExplicitInput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.RequiredInputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                if (!usesInput && binding.Binding.HasExplicitInput)
                    ctx.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.UnusedInputInterface,
                        method.Identifier.GetLocation(), symbol.Name));

                var displayPath = !string.IsNullOrWhiteSpace(inlineSource) ? "<inline>" : sourcePath!;
                ctx.CancellationToken.ThrowIfCancellationRequested();
                var emitted = EmitMethod(symbol, space, binding, projDir, displayPath, ctx.CancellationToken);
                methodSb.AppendLine(emitted);
                emittedCount++;
                runtimeFeatures |= GetRuntimeFacadeFeatures(binding.Binding.ReturnKind);
                if (binding.Binding.LoggerExpression is not null)
                    runtimeFeatures |= RuntimeFacadeFeatures.RunWithLogging;
                if (binding.FingerprintsExpression is not null)
                    runtimeFeatures |= RuntimeFacadeFeatures.FingerprintSupport;
            }
            ctx.CancellationToken.ThrowIfCancellationRequested();
            EmitRuntimeIfNeeded(methodSb, runtimeFeatures, fungeTypes, langVersion);

            if (emittedCount > 0)
                ctx.AddSource(GeneratedMethodsFileName, methodSb.ToString());
        });
    }

    static RuntimeFacadeFeatures GetRuntimeFacadeFeatures(MethodReturnKind returnKind) => returnKind switch
    {
        MethodReturnKind.Void or MethodReturnKind.Int32 => RuntimeFacadeFeatures.RunSync,
        MethodReturnKind.String or MethodReturnKind.NullableString => RuntimeFacadeFeatures.RunString,
        MethodReturnKind.Task => RuntimeFacadeFeatures.RunTask,
        MethodReturnKind.TaskInt32 => RuntimeFacadeFeatures.RunTaskInt,
        MethodReturnKind.TaskString or MethodReturnKind.TaskNullableString => RuntimeFacadeFeatures.RunTaskString,
        MethodReturnKind.ValueTask => RuntimeFacadeFeatures.RunValueTask,
        MethodReturnKind.ValueTaskInt32 => RuntimeFacadeFeatures.RunValueTaskInt,
        MethodReturnKind.ValueTaskString or MethodReturnKind.ValueTaskNullableString => RuntimeFacadeFeatures.RunValueTaskString,
        MethodReturnKind.IEnumerableByte => RuntimeFacadeFeatures.RunEnumerable,
        MethodReturnKind.IAsyncEnumerableByte => RuntimeFacadeFeatures.RunAsyncEnumerable,
        _ => RuntimeFacadeFeatures.None,
    };

    // -----------------------------------------------------------------------
    // Signature binding
    // -----------------------------------------------------------------------

    static FungeExecutionBinding BindExecutionSignature(
        IMethodSymbol method,
        Compilation compilation,
        KnownTypes types,
        KnownFungeTypes fungeTypes,
        string? fingerprintsProviderName = null,
        IMethodSymbol? contextSymbol = null,
        SourceProductionContext? ctx = null)
    {
        var binding = MethodSignatureBinder.Bind(method, types);
        if (!binding.IsValid)
            return new FungeExecutionBinding(binding);

        string? argsExpr = null;
        string? envsExpr = null;

        foreach (var p in binding.UnhandledParameters)
        {
            var type = p.Type;
            // Funge-specific logic: match string array or IEnumerable<string> for args/envs
            var isStringContainer = false;
            if (type is IArrayTypeSymbol arrayType && types.IsString(arrayType.ElementType, false))
            {
                isStringContainer = true;
            }
            else if (type is INamedTypeSymbol namedType && namedType.IsGenericType)
            {
                if (SymbolEqualityComparer.Default.Equals(namedType.ConstructedFrom, types.IEnumerableT)
                    && types.IsString(namedType.TypeArguments[0], false))
                {
                    isStringContainer = true;
                }
            }

            if (isStringContainer)
            {
                var name = p.Name.ToLowerInvariant();
                if (name.Contains("arg"))
                {
                    if (argsExpr is not null)
                        return new(binding, FungeError: new DuplicateInput(p, MethodInputKind.None, p.Locations.FirstOrDefault()));
                    argsExpr = p.Name;
                    continue;
                }
                if (name.Contains("env"))
                {
                    if (envsExpr is not null)
                        return new(binding, FungeError: new DuplicateInput(p, MethodInputKind.None, p.Locations.FirstOrDefault()));
                    envsExpr = p.Name;
                    continue;
                }
            }

            // Still unhandled
            return new(binding, FungeError: new InvalidParameterModifier(p, p.Locations.FirstOrDefault()));
        }

        // Resolve FingerprintsProvider
        string? fingerprintsExpr = null;
        if (!string.IsNullOrWhiteSpace(fingerprintsProviderName) && contextSymbol is not null)
        {
            fingerprintsExpr = ResolveFingerprintsProvider(fingerprintsProviderName!, contextSymbol, method.IsStatic, compilation, types, fungeTypes);
            if (fingerprintsExpr is null && ctx.HasValue)
            {
                ctx.Value.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.InvalidFingerprintsProvider,
                    contextSymbol.Locations.FirstOrDefault(),
                    fingerprintsProviderName,
                    contextSymbol.Name));
            }
        }

        return new(binding, argsExpr, envsExpr, fingerprintsExpr);
    }

    /// <summary>
    /// Resolves a member name to an expression that returns
    /// <c>IEnumerable&lt;IFingerprint&gt;</c> from the containing type.
    /// Returns <c>null</c> if the member is not found or not valid.
    /// </summary>
    static string? ResolveFingerprintsProvider(
        string memberName,
        IMethodSymbol contextSymbol,
        bool isStatic,
        Compilation compilation,
        KnownTypes types,
        KnownFungeTypes fungeTypes)
    {
        if (types.IEnumerableT is null || fungeTypes.IFingerprint is null)
            return null;

        var expectedType = types.IEnumerableT.Construct(fungeTypes.IFingerprint);
        var containingType = contextSymbol.ContainingType;
        var members = containingType.GetMembers(memberName);
        foreach (var member in members)
        {
            switch (member)
            {
                case IMethodSymbol m when m.Parameters.IsEmpty && IsValidFingerprintsProviderType(m.ReturnType, compilation, expectedType):
                    {
                        var qualifier = m.IsStatic ? GetFullyQualifiedTypeName(containingType) : (isStatic ? null : "this");
                        if (qualifier is null && !m.IsStatic) return null; // instance member in static context
                        return qualifier is not null ? $"{qualifier}.{memberName}()" : $"{memberName}()";
                    }
                case IPropertySymbol p when !p.IsIndexer && IsValidFingerprintsProviderType(p.Type, compilation, expectedType):
                    {
                        var qualifier = p.IsStatic ? GetFullyQualifiedTypeName(containingType) : (isStatic ? null : "this");
                        if (qualifier is null && !p.IsStatic) return null;
                        return qualifier is not null ? $"{qualifier}.{memberName}" : memberName;
                    }
            }
        }
        return null;

        static bool IsValidFingerprintsProviderType(ITypeSymbol type, Compilation compilation, INamedTypeSymbol expectedType)
            => compilation.ClassifyConversion(type, expectedType) is { Exists: true, IsImplicit: true };
    }

    static string GetFullyQualifiedTypeName(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace?.IsGlobalNamespace == false
            ? type.ContainingNamespace.ToDisplayString() + "."
            : "";
        return "global::" + ns + type.Name;
    }

    // -----------------------------------------------------------------------
    // Method emit
    // -----------------------------------------------------------------------

    static string EmitMethod(
        IMethodSymbol symbol,
        FungeSpace space,
        FungeExecutionBinding binding,
        string? projDir,
        string sourcePath,
        CancellationToken cancellationToken)
    {
        var ns = symbol.ContainingType.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingType.ContainingNamespace.ToDisplayString() : null;

        var typeKeyword = symbol.ContainingType.TypeKind switch
        {
            TypeKind.Struct when symbol.ContainingType.IsRecord => "record struct",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            TypeKind.Class when symbol.ContainingType.IsRecord => "record",
            _ => "class",
        };

        var typeName = symbol.ContainingType.Name;
        var accessibility = GetAccessibility(symbol.DeclaredAccessibility);
        var staticMod = symbol.IsStatic ? " static" : string.Empty;
        var asyncMod = binding.Binding.ReturnKind == MethodReturnKind.IAsyncEnumerableByte ? " async" : string.Empty;
        var returnTypeSyntax = symbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var paramList = string.Join(", ", symbol.Parameters.Select(p =>
        {
            var prefix = (binding.Binding.IsAsyncEnumerable
                && binding.Binding.CancellationTokenName is not null
                && string.Equals(p.Name, binding.Binding.CancellationTokenName, StringComparison.Ordinal))
                ? $"[{Names.EnumeratorCancellation}] "
                : string.Empty;
            return prefix + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + " " + p.Name;
        }));

        var relPath = projDir is not null ? MakeRelative(projDir, sourcePath) : sourcePath;
        var sb = new StringBuilder();

        if (ns is not null) { sb.Append("namespace ").Append(ns).AppendLine(" {").AppendLine(); }
        sb.Append("partial ").Append(typeKeyword).Append(' ').AppendLine(typeName);
        sb.AppendLine("{");
        sb.AppendLine($"    // Generated from: {relPath}");
        sb.Append("    ").Append(accessibility).Append(staticMod).Append(asyncMod)
            .Append(" partial ").Append(returnTypeSyntax).Append(' ')
            .Append(symbol.Name).Append('(').Append(paramList).AppendLine(")");
        sb.AppendLine("    {");

        EmitBody(sb, space, binding, symbol.IsStatic, cancellationToken);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        if (ns is not null) sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitBody(StringBuilder sb, FungeSpace space, FungeExecutionBinding fungeBinding, bool isStatic, CancellationToken cancellationToken)
    {
        var binding = fungeBinding.Binding;
        var inputExpr = binding.InputKind switch
        {
            MethodInputKind.None => $"{Names.TextReader}.Null",
            MethodInputKind.String => $"new {Names.StringReader}({binding.InputExpression} ?? string.Empty)",
            MethodInputKind.TextReader => binding.InputExpression,
            MethodInputKind.PipeReader => $"new {Names.StreamReader}({binding.InputExpression}.AsStream())",
            _ => $"{Names.TextReader}.Null",
        };
        var cancellationTokenExpr = binding.CancellationTokenName is null
            ? $"{Names.CancellationToken}.None"
            : binding.CancellationTokenName;
        var argsExpr = fungeBinding.ArgsExpression ?? "null";
        var envsExpr = fungeBinding.EnvsExpression ?? "null";

        EmitSpaceData(sb, space, cancellationToken);

        var loggerExpr = "";
        if (binding.LoggerExpression is not null)
        {
            var prefix = (!isStatic && !binding.IsLoggerFromParameter) ? "this." : "";
            loggerExpr = $", logger: {prefix}{binding.LoggerExpression}";
        }

        var fingerprintsExpr = fungeBinding.FingerprintsExpression is not null
            ? $", fingerprints: {fungeBinding.FingerprintsExpression}"
            : "";

        switch (binding.ReturnKind)
        {
            case MethodReturnKind.Void:
                {
                    if (binding.OutputKind == MethodOutputKind.PipeWriter)
                    {
                        sb.AppendLine($"""
                using var __fungeOutput = new {Names.StreamWriter}({binding.OutputExpression}.AsStream(), {Names.Encoding}.UTF8, 1024, leaveOpen: true);
                {Names.FungeRuntime}.RunSync(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == MethodOutputKind.TextWriter
                            ? binding.OutputExpression
                            : $"{Names.TextWriter}.Null";
                        sb.AppendLine($"""
                {Names.FungeRuntime}.RunSync(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                    }
                    break;
                }

            case MethodReturnKind.Int32:
                if (binding.OutputKind == MethodOutputKind.PipeWriter)
                {
                    sb.AppendLine($"""
                using var __fungeOutput = new {Names.StreamWriter}({binding.OutputExpression}.AsStream(), {Names.Encoding}.UTF8, 1024, leaveOpen: true);
                return {Names.FungeRuntime}.RunSync(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                }
                else
                {
                    var outExpr = binding.OutputKind == MethodOutputKind.TextWriter
                        ? binding.OutputExpression
                        : $"{Names.TextWriter}.Null";
                    sb.AppendLine($"""
                return {Names.FungeRuntime}.RunSync(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                }
                break;

            case MethodReturnKind.String:
            case MethodReturnKind.NullableString:
                sb.AppendLine($"""
                return {Names.FungeRuntime}.RunString(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                break;

            case MethodReturnKind.Task:
                {
                    if (binding.OutputKind == MethodOutputKind.PipeWriter)
                    {
                        sb.AppendLine($"""
                using var __fungeOutput = new {Names.StreamWriter}({binding.OutputExpression}.AsStream(), {Names.Encoding}.UTF8, 1024, leaveOpen: true);
                return {Names.FungeRuntime}.RunTask(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == MethodOutputKind.TextWriter
                            ? binding.OutputExpression
                            : $"{Names.TextWriter}.Null";
                        sb.AppendLine($"""
                return {Names.FungeRuntime}.RunTask(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                    }
                    break;
                }

            case MethodReturnKind.TaskInt32:
                if (binding.OutputKind == MethodOutputKind.PipeWriter)
                {
                    sb.AppendLine($$"""
                return __RunTaskIntWithPipeWriter();

                async {{Names.Task}}<int> __RunTaskIntWithPipeWriter()
                {
                    using var __fungeOutput = new {{Names.StreamWriter}}({{binding.OutputExpression}}.AsStream(), {{Names.Encoding}}.UTF8, 1024, leaveOpen: true);
                    return await {{Names.FungeRuntime}}.RunTaskInt(
                        __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {{inputExpr}}, __fungeOutput, {{(binding.HasExplicitInput ? "true" : "false")}}, {{(binding.HasExplicitOutput ? "true" : "false")}}, {{cancellationTokenExpr}}, {{argsExpr}}, {{envsExpr}}{{loggerExpr}}{{fingerprintsExpr}});
                }
        """);
                }
                else
                {
                    var outExpr = binding.OutputKind == MethodOutputKind.TextWriter
                        ? binding.OutputExpression
                        : $"{Names.TextWriter}.Null";
                    sb.AppendLine($"""
                return {Names.FungeRuntime}.RunTaskInt(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                }
                break;

            case MethodReturnKind.TaskString:
            case MethodReturnKind.TaskNullableString:
                sb.AppendLine($"""
                return {Names.FungeRuntime}.RunTaskString(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                break;

            case MethodReturnKind.ValueTask:
                {
                    if (binding.OutputKind == MethodOutputKind.PipeWriter)
                    {
                        sb.AppendLine($"""
                using var __fungeOutput = new {Names.StreamWriter}({binding.OutputExpression}.AsStream(), {Names.Encoding}.UTF8, 1024, leaveOpen: true);
                return {Names.FungeRuntime}.RunValueTask(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, __fungeOutput, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                    }
                    else
                    {
                        var outExpr = binding.OutputKind == MethodOutputKind.TextWriter
                            ? binding.OutputExpression
                            : $"{Names.TextWriter}.Null";
                        sb.AppendLine($"""
                return {Names.FungeRuntime}.RunValueTask(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                    }
                    break;
                }

            case MethodReturnKind.ValueTaskInt32:
                if (binding.OutputKind == MethodOutputKind.PipeWriter)
                {
                    sb.AppendLine($$"""
                return __RunValueTaskIntWithPipeWriter();
        
                async {{Names.ValueTask}}<int> __RunValueTaskIntWithPipeWriter()
                {
                    using var __fungeOutput = new {{Names.StreamWriter}}({{binding.OutputExpression}}.AsStream(), {{Names.Encoding}}.UTF8, 1024, leaveOpen: true);
                    return await {{Names.FungeRuntime}}.RunValueTaskInt(
                        __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {{inputExpr}}, __fungeOutput, {{(binding.HasExplicitInput ? "true" : "false")}}, {{(binding.HasExplicitOutput ? "true" : "false")}}, {{cancellationTokenExpr}}, {{argsExpr}}, {{envsExpr}}{{loggerExpr}}{{fingerprintsExpr}});
                }
        """);
                }
                else
                {
                    var outExpr = binding.OutputKind == MethodOutputKind.TextWriter
                        ? binding.OutputExpression
                        : $"{Names.TextWriter}.Null";
                    sb.AppendLine($"""
                return {Names.FungeRuntime}.RunValueTaskInt(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {outExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                }
                break;

            case MethodReturnKind.ValueTaskString:
            case MethodReturnKind.ValueTaskNullableString:
                sb.AppendLine($"""
                return {Names.FungeRuntime}.RunValueTaskString(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr});
        """);
                break;

            case MethodReturnKind.IEnumerableByte:
                sb.AppendLine($"""
                foreach (var __b in {Names.FungeRuntime}.RunEnumerable(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr}))
                    yield return __b;
        """);
                break;

            case MethodReturnKind.IAsyncEnumerableByte:
                sb.AppendLine($"""
                await foreach (var __b in {Names.FungeRuntime}.RunAsyncEnumerable(
                    __cells, __minX, __minY, __minZ, __maxX, __maxY, __maxZ, {inputExpr}, {(binding.HasExplicitInput ? "true" : "false")}, {(binding.HasExplicitOutput ? "true" : "false")}, {cancellationTokenExpr}, {argsExpr}, {envsExpr}{loggerExpr}{fingerprintsExpr}))
                    yield return __b;
        """);
                break;
        }
    }

    static void EmitSpaceData(StringBuilder sb, FungeSpace space, CancellationToken cancellationToken)
    {
        sb.AppendLine($"""
                int __minX = {space.MinX}, __minY = {space.MinY}, __minZ = {space.MinZ}, __maxX = {space.MaxX}, __maxY = {space.MaxY}, __maxZ = {space.MaxZ};
                var __cells = new {Names.Dictionary}<(int, int, int), int>();
        """);
        for (var z = space.MinZ; z <= space.MaxZ; z++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            for (var y = space.MinY; y <= space.MaxY; y++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                for (var x = space.MinX; x <= space.MaxX; x++)
                {
                    var val = space[new FungeVector(x, y, z)];
                    if (val != ' ')
                        sb.AppendLine($"""
                __cells[({x}, {y}, {z})] = {val};
        """);
                }
            }
        }
    }

    // -----------------------------------------------------------------------
    // I/O scan
    // -----------------------------------------------------------------------

    static (bool usesOutput, bool usesInput) ScanFungeIo(FungeSpace space, CancellationToken cancellationToken)
    {
        bool usesOutput = false, usesInput = false;
        for (var z = space.MinZ; z <= space.MaxZ; z++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            for (var y = space.MinY; y <= space.MaxY; y++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                for (var x = space.MinX; x <= space.MaxX; x++)
                {
                    var c = space[new FungeVector(x, y, z)];
                    if (c is '.' or ',') usesOutput = true;
                    if (c is '&' or '~') usesInput = true;
                    if (usesOutput && usesInput) return (true, true);
                }
            }
        }
        return (usesOutput, usesInput);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Protected => "protected",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => string.Empty,
    };

    static bool IsLanguageVersionAtLeastCSharp8(LanguageVersion v) => v switch
    {
        LanguageVersion.Default or LanguageVersion.Latest or LanguageVersion.Preview or LanguageVersion.LatestMajor => true,
        _ => v >= LanguageVersion.CSharp8,
    };

    static string NormalizePath(string path) => path.Replace('\\', '/').TrimStart('/');

    static string MakeRelative(string baseDir, string fullPath)
    {
        var sep = Path.DirectorySeparatorChar.ToString();
        if (!baseDir.EndsWith(sep)) baseDir += sep;
        return fullPath.StartsWith(baseDir, StringComparison.OrdinalIgnoreCase)
            ? fullPath[baseDir.Length..]
            : fullPath;
    }
}
