using System.Text;

namespace Esolang.Funge.Generator;

partial class MethodGenerator
{
    const string FungeRuntimeFileName = "FungeRuntime.g.cs";

    static void EmitRuntimeIfNeeded(Microsoft.CodeAnalysis.SourceProductionContext ctx, bool needed)
    {
        if (!needed) return;
        ctx.AddSource(FungeRuntimeFileName, BuildRuntimeSource());
    }

    static string BuildRuntimeSource() => """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS1591
        using System;
        using System.Collections.Generic;
        using System.IO;

        namespace Esolang.Funge.__Generated
        {
            internal static class FungeRuntime
            {
                internal static void Run(
                    Dictionary<(int, int), int> cells,
                    int minX, int minY, int maxX, int maxY,
                    TextReader input,
                    TextWriter output)
                {
                    int px = 0, py = 0, dx = 1, dy = 0;
                    bool stringMode = false;
                    var stack = new List<int>();
                    var rng = new Random();

                    int GetCell(int x, int y) => cells.TryGetValue((x, y), out var v) ? v : ' ';
                    void SetCell(int x, int y, int val)
                    {
                        if (val == ' ') cells.Remove((x, y));
                        else cells[(x, y)] = val;
                    }
                    int Pop() { if (stack.Count == 0) return 0; var v = stack[stack.Count - 1]; stack.RemoveAt(stack.Count - 1); return v; }
                    void Push(int v) => stack.Add(v);

                    (int nx, int ny) Advance(int x, int y, int ddx, int ddy)
                    {
                        if (maxX < minX) return (x, y);
                        int nx = x + ddx, ny = y + ddy;
                        int w = maxX - minX + 1, h = maxY - minY + 1;
                        if (nx < minX) nx = maxX - ((minX - nx - 1) % w);
                        else if (nx > maxX) nx = minX + ((nx - maxX - 1) % w);
                        if (ny < minY) ny = maxY - ((minY - ny - 1) % h);
                        else if (ny > maxY) ny = minY + ((ny - maxY - 1) % h);
                        return (nx, ny);
                    }

                    while (true)
                    {
                        int cell = GetCell(px, py);
                        if (stringMode) { if (cell == '"') stringMode = false; else Push(cell); (px, py) = Advance(px, py, dx, dy); continue; }
                        bool suppressAdvance = false;
                        switch (cell)
                        {
                            case ' ': case 'z': break;
                            case '!': Push(Pop() == 0 ? 1 : 0); break;
                            case '$': Pop(); break;
                            case ':': { int v = Pop(); Push(v); Push(v); break; }
                            case '\\': { int b = Pop(), a = Pop(); Push(b); Push(a); break; }
                            case 'n': stack.Clear(); break;
                            case '+': { int b = Pop(), a = Pop(); Push(a + b); break; }
                            case '-': { int b = Pop(), a = Pop(); Push(a - b); break; }
                            case '*': { int b = Pop(), a = Pop(); Push(a * b); break; }
                            case '/': { int b = Pop(), a = Pop(); Push(b == 0 ? 0 : a / b); break; }
                            case '%': { int b = Pop(), a = Pop(); Push(b == 0 ? 0 : a % b); break; }
                            case '`': { int b = Pop(), a = Pop(); Push(a > b ? 1 : 0); break; }
                            case '0': case '1': case '2': case '3': case '4':
                            case '5': case '6': case '7': case '8': case '9': Push(cell - '0'); break;
                            case 'a': Push(10); break; case 'b': Push(11); break; case 'c': Push(12); break;
                            case 'd': Push(13); break; case 'e': Push(14); break; case 'f': Push(15); break;
                            case '>': dx = 1; dy = 0; break;
                            case '<': dx = -1; dy = 0; break;
                            case '^': dx = 0; dy = -1; break;
                            case 'v': dx = 0; dy = 1; break;
                            case '?':
                                switch (rng.Next(4)) { case 0: dx=1;dy=0;break; case 1:dx=-1;dy=0;break; case 2:dx=0;dy=-1;break; default:dx=0;dy=1;break; }
                                break;
                            case '_': { int v = Pop(); dx = v == 0 ? 1 : -1; dy = 0; break; }
                            case '|': { int v = Pop(); dy = v == 0 ? 1 : -1; dx = 0; break; }
                            case '[': { int ndx = dy, ndy = -dx; dx = ndx; dy = ndy; break; }
                            case ']': { int ndx = -dy, ndy = dx; dx = ndx; dy = ndy; break; }
                            case 'r': dx = -dx; dy = -dy; break;
                            case 'x': { int ndy = Pop(), ndx = Pop(); dx = ndx; dy = ndy; break; }
                            case 'w': { int b = Pop(), a = Pop(); if(a>b){int ndx=-dy,ndy=dx;dx=ndx;dy=ndy;}else if(a<b){int ndx=dy,ndy=-dx;dx=ndx;dy=ndy;} break; }
                            case '#': (px, py) = Advance(px, py, dx, dy); break;
                            case 'j':
                            {
                                int s = Pop(); int jdx = s >= 0 ? dx : -dx, jdy = s >= 0 ? dy : -dy, abs = s < 0 ? -s : s;
                                for (int i = 0; i < abs; i++) (px, py) = Advance(px, py, jdx, jdy);
                                suppressAdvance = true; break;
                            }
                            case ';':
                                (px, py) = Advance(px, py, dx, dy);
                                while (GetCell(px, py) != ';') (px, py) = Advance(px, py, dx, dy);
                                break;
                            case '\'': (px, py) = Advance(px, py, dx, dy); Push(GetCell(px, py)); break;
                            case 's': { int sv = Pop(); (px, py) = Advance(px, py, dx, dy); SetCell(px, py, sv); break; }
                            case '"': stringMode = true; break;
                            case 'g': { int gy = Pop(), gx = Pop(); Push(GetCell(gx, gy)); break; }
                            case 'p': { int gy = Pop(), gx = Pop(), pv = Pop(); SetCell(gx, gy, pv); break; }
                            case '.': output.Write(Pop()); output.Write(' '); break;
                            case ',': output.Write((char)Pop()); break;
                            case '&': { var line = input.ReadLine(); if(line==null){dx=-dx;dy=-dy;}else Push(int.TryParse(line.Trim(),out int iv)?iv:0); break; }
                            case '~': { int ch = input.Read(); if(ch<0){dx=-dx;dy=-dy;}else Push(ch); break; }
                            case '@': return;
                            case 'q': return;
                            default: if (cell >= 'A' && cell <= 'Z') { dx = -dx; dy = -dy; } break;
                        }
                        if (!suppressAdvance) (px, py) = Advance(px, py, dx, dy);
                    }
                }
            }
        }
        """;
}
