<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net48;net8.0;net9.0;net10.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(OS)' != 'Windows_NT'">net8.0;net9.0;net10.0</TargetFrameworks>
    <AssemblyName>Esolang.Funge.Fingerprints.Time.Tests</AssemblyName>
    <RootNamespace>Esolang.Funge.Fingerprints.Time</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fingerprints.Time\Esolang.Funge.Fingerprints.Time.csproj" />
  </ItemGroup>

</Project>
