<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <AssemblyName>Funge.Processor.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fingerprints.Arry\Esolang.Funge.Fingerprints.Arry.csproj" />
    <ProjectReference Include="..\Fingerprints.Imth\Esolang.Funge.Fingerprints.Imth.csproj" />
    <ProjectReference Include="..\Fingerprints.Fixp\Esolang.Funge.Fingerprints.Fixp.csproj" />
    <ProjectReference Include="..\Fingerprints.Indv\Esolang.Funge.Fingerprints.Indv.csproj" />
    <ProjectReference Include="..\Fingerprints.Long\Esolang.Funge.Fingerprints.Long.csproj" />
    <ProjectReference Include="..\Parser\Esolang.Funge.Parser.csproj" />
    <ProjectReference Include="..\Processor\Esolang.Funge.Processor.csproj" />
    <ProjectReference Include="..\Abstractions\Esolang.Funge.Abstractions.csproj" />
    <ProjectReference Include="..\Fingerprints.Base\Esolang.Funge.Fingerprints.Base.csproj" />
  </ItemGroup>


  <ItemGroup Condition="'$(TargetFramework)' != 'net48'">
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" />
  </ItemGroup>

</Project>
